/*
 * Copyright 2025 The Closure Compiler Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.javascript.jscomp;

import static com.google.common.base.Preconditions.checkArgument;
import static com.google.common.base.Preconditions.checkNotNull;
import static com.google.common.base.Preconditions.checkState;
import static com.google.javascript.jscomp.AstFactory.type;

import com.google.common.annotations.VisibleForTesting;
import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableSet;
import com.google.common.collect.Iterables;
import com.google.errorprone.annotations.CanIgnoreReturnValue;
import com.google.javascript.jscomp.ExpressionDecomposer.DecompositionType;
import com.google.javascript.jscomp.colors.StandardColors;
import com.google.javascript.jscomp.js.RuntimeJsLibManager;
import com.google.javascript.jscomp.parsing.parser.FeatureSet;
import com.google.javascript.jscomp.parsing.parser.FeatureSet.Feature;
import com.google.javascript.rhino.IR;
import com.google.javascript.rhino.JSDocInfo;
import com.google.javascript.rhino.Node;
import com.google.javascript.rhino.Token;
import com.google.javascript.rhino.jstype.JSTypeNative;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Supplier;
import org.jspecify.annotations.Nullable;

/**
 * Normalizes ES6 classes to a simpler form for easier optimization.
 *
 * <p>This pass handles four main transformations which are performed when needed:
 *
 * <ol>
 *   <li>Extracts class extends expressions into variables.
 *   <li>Extracts classes into variables.
 *   <li>Rewrites static class field initializers and static blocks into a static initialization
 *       method that is called after class definition.
 *   <li>If transpilation of {@link Feature#PUBLIC_CLASS_FIELDS} is needed, rewrites public class
 *       instance fields into assignments in the constructor and removes static field declarations.
 * </ol>
 *
 * <p>These transformations must be done before passes like {@link Es6RewriteClass} and {@link
 * Es6ConvertSuper}, which only handle classes in simpler forms.
 */
public final class Es6NormalizeClasses implements NodeTraversal.ScopedCallback, CompilerPass {
  private static final String CLASS_DECL_VAR = "$jscomp$classDecl$";
  private static final String CLASS_EXTENDS_VAR = "$jscomp$classExtends$";
  private static final String COMP_FIELD_VAR = "$jscomp$compField$";
  private static final String STATIC_INIT_METHOD_NAME = "$jscomp$staticInit$";
  private static final String PRIVATE_MAP_VAR = "$jscomp$privateMap$";
  private static final String STATIC_PRIVATE_MAP_VAR = "$jscomp$staticPrivateMap$";
  private static final String PRIVATE_PROTO_VAR = "$jscomp$priv$proto$";
  private static final String PRIVATE_VAR = "$jscomp$priv$";
  private static final String TMP_VAR = "$jscomp$tmp$";

  public static final DiagnosticType ILLEGAL_PRIVATE_MEMBER_ASSIGNMENT =
      DiagnosticType.error(
          "JSC_ILLEGAL_PRIVATE_MEMBER_ASSIGNMENT",
          "Invalid assignment to private method ''#{0}''. Private methods cannot be reassigned.");

  /**
   * Mapping from generic placeholder names used in unit tests to the variable name prefixes
   * generated by class normalization and rewriting passes.
   *
   * <p>Used in unit tests via {@code setGenericNameReplacements} so that test expected output can
   * use readable placeholder names (such as {@code CLASS_DECL} or {@code PRIVATE}) rather than
   * hardcoding compiler-generated variable names.
   */
  @VisibleForTesting
  static final ImmutableMap<String, String> GENERIC_NAME_REPLACEMENTS =
      ImmutableMap.<String, String>builder()
          .put("CLASS_DECL", CLASS_DECL_VAR)
          .put("CLASS_EXTENDS", CLASS_EXTENDS_VAR)
          .put("COMP_FIELD", COMP_FIELD_VAR)
          .put("STATIC_INIT", STATIC_INIT_METHOD_NAME)
          .put("STATIC_PRIVATE_MAP", STATIC_PRIVATE_MAP_VAR)
          .put("PRIVATE_MAP", PRIVATE_MAP_VAR)
          .put("PRIVATE_PROTO", PRIVATE_PROTO_VAR)
          .put("PRIVATE", PRIVATE_VAR)
          .put("TMP", TMP_VAR)
          .buildOrThrow();

  /** Returns $jscomp$tmp$[FILE_ID]$[number] */
  private String generateUniqueTmpVarName(NodeTraversal t) {
    return TMP_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$classDecl$[FILE_ID]$[number] */
  private String generateUniqueClassDeclVarName(NodeTraversal t) {
    return CLASS_DECL_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$classExtends$[FILE_ID]$[number] */
  private String generateUniqueClassExtendsVarName(NodeTraversal t) {
    return CLASS_EXTENDS_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$compfield$[FILE_ID]$[number] */
  private String generateUniqueCompFieldVarName(NodeTraversal t) {
    return COMP_FIELD_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$staticInit$[FILE_ID]$[number] */
  private String generateUniqueStaticInitMethodName(NodeTraversal t) {
    return STATIC_INIT_METHOD_NAME + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$privateMap$[FILE_ID]$[number] */
  private static String generateUniquePrivateMapVarName(
      AbstractCompiler compiler, NodeTraversal t) {
    return PRIVATE_MAP_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$staticPrivateMap$[FILE_ID]$[number] */
  private static String generateUniqueStaticPrivateMapVarName(
      AbstractCompiler compiler, NodeTraversal t) {
    return STATIC_PRIVATE_MAP_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$priv$proto$[FILE_ID]$[number] */
  private static String generateUniquePrivateProtoVarName(
      AbstractCompiler compiler, NodeTraversal t) {
    return PRIVATE_PROTO_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  /** Returns $jscomp$priv$[FILE_ID]$[number] */
  private static String generateUniquePrivateVarName(AbstractCompiler compiler, NodeTraversal t) {
    return PRIVATE_VAR + compiler.getUniqueIdSupplier().getUniqueId(t.getInput());
  }

  private final AbstractCompiler compiler;
  private final AstFactory astFactory;
  private final ExpressionDecomposer expressionDecomposer;
  private final SynthesizeExplicitConstructors ctorCreator;
  private final boolean transpileClassFields;
  private final boolean transpilePrivateClassFields;

  private final boolean doStaticInheritanceRewrites;
  private final boolean doStaticSuperRewrites;
  private final RuntimeJsLibManager.JsLibField jscompPrivateMap;

  Es6NormalizeClasses(AbstractCompiler compiler) {
    this.compiler = compiler;
    astFactory = compiler.createAstFactory();
    expressionDecomposer = compiler.createDefaultExpressionDecomposer();
    ctorCreator = new SynthesizeExplicitConstructors(compiler);
    // Note: This covers both public fields as well as static fields (they launched together).
    var options = compiler.getOptions();
    transpileClassFields = options.needsTranspilationOf(Feature.PUBLIC_CLASS_FIELDS);
    transpilePrivateClassFields = options.needsTranspilationOf(Feature.PRIVATE_ELEMENTS);

    doStaticInheritanceRewrites =
        options.getAssumeStaticInheritanceIsNotUsed() && !options.getSkipNonTranspilationPasses();

    // Es6ConvertSuper handles static super rewrites otherwise.
    doStaticSuperRewrites = !options.needsTranspilationOf(Feature.SUPER);
    jscompPrivateMap = compiler.getRuntimeJsLibManager().getJsLibField("$jscomp.PrivateMap");
  }

  @Override
  public void process(Node externs, Node root) {
    NodeTraversal.traverseRoots(compiler, this, externs, root);

    // We transpiled away class static blocks. We always do this, regardless of language out, to
    // normalize the AST.
    FeatureSet transpiledFeatures = FeatureSet.BARE_MINIMUM.with(Feature.CLASS_STATIC_BLOCK);
    if (transpileClassFields) {
      // We removed public and static field declarations if they need transpilation.
      transpiledFeatures = transpiledFeatures.with(Feature.PUBLIC_CLASS_FIELDS);
    }
    if (transpilePrivateClassFields) {
      transpiledFeatures = transpiledFeatures.with(Feature.PRIVATE_ELEMENTS);
    }
    TranspilationPasses.maybeMarkFeaturesAsTranspiledAway(compiler, root, transpiledFeatures);
    // Update the compiler's summary of getter and setter property names in the AST since class
    // getter/setter definitions may have been detached or rewritten into normal
    // methods/descriptors.
    GatherGetterAndSetterProperties.update(compiler, externs, root);
  }

  private final Deque<ClassRecord> classStack = new ArrayDeque<>();

  @Override
  public boolean shouldTraverse(NodeTraversal t, Node n, Node parent) {
    switch (n.getToken()) {
      case SCRIPT -> {
        FeatureSet scriptFeatures = NodeUtil.getFeatureSetOfScript(n);
        return scriptFeatures == null
            || scriptFeatures.contains(Feature.CLASSES)
            || scriptFeatures.contains(Feature.CLASS_STATIC_BLOCK)
            || scriptFeatures.contains(Feature.PUBLIC_CLASS_FIELDS)
            || scriptFeatures.contains(Feature.PRIVATE_ELEMENTS);
      }
      case CLASS -> {
        // The class name for declarations and class expression inner names.
        Optional<Node> bindingIdentifier =
            n.getFirstChild().isName() ? Optional.of(n.getFirstChild()) : Optional.empty();

        // Generate any needed normalized class names in pre-order so that we can rewrite the inner
        // class name to the new outer name if needed.
        // (We don't actually do the normalization in pre-order because that can cause
        // NodeTraversal to skip traversing other parts of the AST.)
        NormalizedNames normalized = generateNormalizedClassNames(t, n);

        ClassRecord record = new ClassRecord(normalized, bindingIdentifier, /* classNode= */ n);
        Node classMembers = n.getLastChild();
        if (classMembers.isClassMembers()) {
          // Pre-scan all class members (fields, methods, accessors) upon entering the CLASS node
          // to record all private identifiers (#member) declared within the class body.
          // Pre-registering private declarations up front ensures that forward brand checks
          // (e.g., `#field in this` inside a method defined above `#field`) and cross-member
          // references can resolve the private member record regardless of AST traversal order.
          for (Node member = classMembers.getFirstChild();
              member != null;
              member = member.getNext()) {
            if (isPrivateMember(member)) {
              record.recordPrivateMember(member);
            }
          }
        }
        classStack.addFirst(record);
      }
      case COMPUTED_FIELD_DEF -> {
        checkState(!classStack.isEmpty());
        var classRecord = classStack.peek();
        classRecord.maybeRecordComputedPropWithSideEffects(n);
        classRecord.recordField(n);
      }
      case MEMBER_FIELD_DEF -> {
        checkState(!classStack.isEmpty());
        var classRecord = classStack.peek();
        if (n.isPrivateIdentifier()) {
          classRecord.recordPrivateMember(n);
        }
        classRecord.recordField(n);
      }
      case MEMBER_FUNCTION_DEF, GETTER_DEF, SETTER_DEF -> {
        if (n.isPrivateIdentifier()) {
          checkState(!classStack.isEmpty());
          classStack.peek().recordPrivateMember(n);
        }
      }
      case BLOCK -> {
        if (!NodeUtil.isClassStaticBlock(n)) {
          break;
        }

        checkState(!classStack.isEmpty());
        classStack.peek().recordStaticBlock(n);
      }
      // For example, a class method with a computed property name.
      case COMPUTED_PROP -> {
        if (!n.getParent().isClassMembers()) {
          break;
        }

        checkState(!classStack.isEmpty());
        classStack.peek().maybeRecordComputedPropWithSideEffects(n);
      }
      default -> {}
    }
    return true;
  }

  private boolean shouldExtractExtends(Node classNode) {
    checkArgument(classNode.isClass());
    Node superClassNode = classNode.getSecondChild();
    return !superClassNode.isEmpty() && !superClassNode.isQualifiedName();
  }

  /**
   * Find common cases where we can safely decompose class extends expressions which are not
   * qualified names. Enables transpilation of complex extends expressions.
   *
   * <p>We can only decompose the expression in a limited set of cases to avoid changing evaluation
   * order of side-effect causing statements.
   */
  private boolean canExtractExtendsSimply(Node classNode) {
    Node enclosingStatement = checkNotNull(NodeUtil.getEnclosingStatement(classNode), classNode);
    if (enclosingStatement == classNode) {
      // `class Foo extends some_expression {}`
      return true;
    }

    Node classNodeParent = classNode.getParent();
    if (NodeUtil.isNameDeclaration(enclosingStatement)
        && classNodeParent.isName()
        && classNodeParent.isFirstChildOf(enclosingStatement)) {
      // `const Foo = class extends some_expression {}, maybe_other_var;`
      return true;
    }

    if (enclosingStatement.isExprResult()
        && classNodeParent.isOnlyChildOf(enclosingStatement)
        && classNodeParent.isAssign()
        && classNode.isSecondChildOf(classNodeParent)) {
      // `lhs = class extends some_expression {};`
      Node lhsNode = classNodeParent.getFirstChild();
      // We can extract a temporary variable for some_expression as long as lhs expression
      // has no side effects.
      return !compiler.getAstAnalyzer().mayHaveSideEffects(lhsNode);
    }

    return false;
  }

  private void extractExtends(NodeTraversal t, ClassRecord classRecord) {
    Node classNode = classRecord.classNode;

    Node statement = NodeUtil.getEnclosingStatement(classNode);
    Node originalExtends = classNode.getSecondChild();

    // If the extracted superclass is itself a named class expression, remove its inner name to
    // avoid creating a new, useless variable in the scope.
    if (originalExtends.isClass() && originalExtends.getFirstChild().isName()) {
      originalExtends
          .getFirstChild()
          .replaceWith(IR.empty().srcref(originalExtends.getFirstChild()));
    }

    Node nameNode = classRecord.normalizedNames.superClassNode.get();
    originalExtends.replaceWith(nameNode);
    Node extendsAlias = IR.constNode(nameNode.cloneNode(), originalExtends).srcref(originalExtends);
    extendsAlias.insertBefore(statement);
    NodeUtil.addFeatureToScript(
        NodeUtil.getEnclosingScript(classNode), Feature.CONST_DECLARATIONS, compiler);
    t.reportCodeChange(classNode);
  }

  /** Replaces a node with an IIFE that returns that node. */
  private void pushDownNodeIntoNewIife(Node n) {
    // Create the shell of the IIFE.
    Node functionBody = IR.block();
    Node arrowFn = IR.arrowFunction(IR.name(""), IR.paramList(), functionBody).srcref(n);
    arrowFn.setColor(StandardColors.UNKNOWN);
    Node iife = astFactory.createCallWithUnknownType(arrowFn).srcrefTreeIfMissing(n);

    // This replaces n with the IIFE and detaches n from the AST.
    n.replaceWith(iife);

    // Now that n is detached, it's safe to make it the child of the RETURN node.
    functionBody.addChildToBack(astFactory.createReturn(n).srcref(n));

    NodeUtil.addFeatureToScript(
        NodeUtil.getEnclosingScript(iife), Feature.ARROW_FUNCTIONS, compiler);

    compiler.reportChangeToEnclosingScope(iife);
  }

  /**
   * Determines if a class node needs to be extracted into a separate variable declaration.
   *
   * <p>Extraction is necessary for class expressions in contexts where their side effects or
   * structure might interfere with subsequent transpilation passes. However, some forms of class
   * expressions are already handled correctly by other parts of the transpilation, specifically
   * {@code Es6ToEs3Converter.ClassDeclarationMetadata#create}.
   */
  private boolean shouldExtractClass(Node classNode) {
    Node parent = classNode.getParent();
    if (NodeUtil.isClassDeclaration(classNode)
        || parent.isName()
        || (parent.isAssign()
            && parent.getFirstChild().isQualifiedName()
            && parent.getParent().isExprResult())) {
      // No need to extract. Handled directly by Es6ToEs3Converter.ClassDeclarationMetadata#create.
      return false;
    }

    return true;
  }

  private void extractClass(NodeTraversal t, ClassRecord classRecord) {
    Node classNode = classRecord.classNode;
    Node parent = classNode.getParent();

    JSDocInfo info = NodeUtil.getBestJSDocInfo(classNode);

    Node statement = NodeUtil.getEnclosingStatement(parent);
    // class name node used as LHS in newly created assignment
    Node classNameLhs = classRecord.createNewNameReferenceNode();
    // class name node that replaces the class literal in the original statement
    Node classNameRhs = classNameLhs.cloneTree();
    classNode.replaceWith(classNameRhs);
    Node classDeclaration = IR.constNode(classNameLhs, classNode).srcrefTreeIfMissing(classNode);
    NodeUtil.addFeatureToScript(t.getCurrentScript(), Feature.CONST_DECLARATIONS, compiler);
    classDeclaration.setJSDocInfo(JSDocInfo.Builder.maybeCopyFrom(info).build());
    classDeclaration.insertBefore(statement);

    // If the original statement was a variable declaration or qualified name assignment like
    // like these:
    // var ClassName = class {...
    // OR
    // some.qname.ClassName = class {...
    //
    // We will have changed the original statement to
    //
    // var ClassName = generatedName;
    // OR
    // some.qname.ClassName = generatedName;
    //
    // This is creating a type alias for a class, but since there's no literal class on the RHS,
    // it doesn't look like one. Add at-constructor JSDoc to make it clear that this is happening.
    //
    // This was added to fix a specific problem where the original definition was for an abstract
    // class, so its JSDoc included at-abstract.
    // This caused ClosureCodeRemoval to think this rewritten assignment was a removable abstract
    // method definition instead of the definition of an abstract class.
    //
    // TODO(b/117292942): Make ClosureCodeRemoval smarter so this hack isn't necessary to
    // prevent incorrect removal of assignments.
    if (NodeUtil.isNameDeclaration(statement)
        && statement.hasOneChild()
        && statement.getOnlyChild() == parent) {
      // var ClassName = generatedName;
      addAtConstructor(statement);
    } else if (statement.isExprResult()) {
      Node expr = statement.getOnlyChild();
      if (expr.isAssign()
          && expr.getFirstChild().isQualifiedName()
          && expr.getSecondChild() == classNameRhs) {
        // some.qname.ClassName = generatedName;
        addAtConstructor(expr);
      }
    }
    compiler.reportChangeToEnclosingScope(classDeclaration);
  }

  /** Add at-constructor to the JSDoc of the given node. */
  private void addAtConstructor(Node node) {
    JSDocInfo.Builder builder = JSDocInfo.Builder.maybeCopyFrom(node.getJSDocInfo());
    builder.recordConstructor();
    node.setJSDocInfo(builder.build());
  }

  /**
   * Gets the location of the statement declaring the class
   *
   * @return null if the class cannot be extracted
   */
  private @Nullable Node getStatementDeclaringClass(Node classNode, Node classNameNode) {
    if (NodeUtil.isClassDeclaration(classNode)) {
      // `class C {}` -> can use `C.staticMember` to extract static fields
      checkState(NodeUtil.isStatement(classNode));
      return classNode;
    }
    final Node parent = classNode.getParent();
    if (parent.isName()) {
      // `let C = class {};`
      // We can use `C.staticMemberName = ...` to extract static fields
      checkState(parent == classNameNode);
      checkState(NodeUtil.isStatement(classNameNode.getParent()));
      return classNameNode.getParent();
    }
    if (parent.isAssign()
        && parent.getFirstChild() == classNameNode
        && parent.getParent().isExprResult()) {
      // `something.C = class {}`
      // we can use `something.C.staticMemberName = ...` to extract static fields
      checkState(NodeUtil.isStatement(classNameNode.getGrandparent()));
      return classNameNode.getGrandparent();
    }
    return null;
  }

  @Override
  public void enterScope(NodeTraversal t) {
    Node scopeRoot = t.getScopeRoot();
    if (NodeUtil.isFunctionBlock(scopeRoot) && NodeUtil.isEs6Constructor(scopeRoot.getParent())) {
      classStack.peek().recordConstructorScope(t.getScope());
    }
  }

  @Override
  public void exitScope(NodeTraversal t) {}

  @Override
  public void visit(NodeTraversal t, Node n, Node parent) {
    switch (n.getToken()) {
      case IN -> {
        if (transpilePrivateClassFields && n.getFirstChild().isPrivateIdentifier()) {
          rewritePrivateIn(t, n);
        }
      }
      case GETPROP, OPTCHAIN_GETPROP -> {
        if (transpilePrivateClassFields && n.isPrivateIdentifier()) {
          rewritePrivateGetProp(t, n);
        }
      }
      case CLASS -> {
        ClassRecord currClassRecord = classStack.removeFirst();
        checkState(currClassRecord.classNode == n, "unexpected node: %s", n);

        // First, rewrite complex extends expressions. This must happen before class extraction
        // to ensure the class's structure is simplified first.
        if (currClassRecord.normalizedNames.shouldExtractExtends) {
          if (!canExtractExtendsSimply(n)) {
            // When a class is used in an expressions where adding an alias as the previous
            // statement might change execution order of a side-effect causing statement, wrap the
            // class in an IIFE so that decomposition can happen safely.
            pushDownNodeIntoNewIife(n);

            // The parent of the class has been updated so reflect that.
            parent = n.getParent();
          }
          extractExtends(t, currClassRecord);
        }

        // Second, extract the class itself if it's in an expression context or it needs a name.
        if (currClassRecord.normalizedNames.shouldExtractClass) {
          if (expressionDecomposer.canExposeExpression(n) != DecompositionType.MOVABLE) {
            // When class is not movable, we wrap it inside an IIFE. We have observed unsafe
            // circumstances where decomposing causes issues so this is safer. See b/417772606.
            pushDownNodeIntoNewIife(n);
          }
          extractClass(t, currClassRecord);

          // The parent of the class has been updated so reflect that.
          parent = n.getParent();
        }

        Node classNameNode = NodeUtil.getNameNode(n);
        checkState(classNameNode != null, "Class missing a name: %s", n);
        Node classInsertionPoint = getStatementDeclaringClass(n, classNameNode);
        checkState(classInsertionPoint != null, "Class was not extracted: %s", n);

        // For class expressions, remove the inner name if it's present.
        // Note: Safe because we removed all static initialization logic, ensured the class has a
        // name, and we replaced all references to the inner class name.
        if (currClassRecord.bindingIdentifier.isPresent()
            && (parent.isName() || parent.isAssign())) {
          n.getFirstChild().replaceWith(IR.empty().srcref(n.getFirstChild()));
          compiler.reportChangeToEnclosingScope(n);
        }

        if (transpilePrivateClassFields
            && (currClassRecord.hasInstancePrivateMembers
                || currClassRecord.hasStaticPrivateMembers)) {
          insertPrivateDeclarations(t, currClassRecord, classInsertionPoint);
        }

        // Rewrite parts of the class based on the record.
        rewriteSideEffectedComputedProps(t, currClassRecord, classInsertionPoint);
        if (transpileClassFields
            || (transpilePrivateClassFields && currClassRecord.hasInstancePrivateMembers)) {
          rewriteInstanceMembers(t, currClassRecord);
        }
        rewriteStaticMembers(t, currClassRecord, classInsertionPoint);
      }
      case NAME -> maybeUpdateClassSelfRef(t, n);
      case THIS, SUPER -> visitThisAndSuper(t, n);
      default -> {}
    }
  }

  /**
   * Inserts declarations for the {@code PrivateMap} objects before the class statement if the class
   * contains private members.
   */
  private void insertPrivateDeclarations(
      NodeTraversal t, ClassRecord record, Node classInsertionPoint) {
    NodeUtil.addFeatureToScript(t.getCurrentScript(), Feature.CONST_DECLARATIONS, compiler);
    // Create const PRIVATE_MAP$uid = new $jscomp.PrivateMap() declaration for instance private
    // members.
    if (record.hasInstancePrivateMembers) {
      compiler.getRuntimeJsLibManager().injectLibForField("$jscomp.PrivateMap");
      Node mapVar =
          astFactory
              .createSingleConstNameDeclaration(
                  record.getPrivateMapVarName(compiler, t),
                  astFactory.createNewNode(astFactory.createQNameWithUnknownType(jscompPrivateMap)))
              .srcrefTreeIfMissing(record.classNode);
      mapVar.insertBefore(classInsertionPoint);

      // Create const PRIVATE_PROTO$uid = Object.create(null, ...) declaration for instance private
      // methods and accessors.
      if (record.hasInstancePrivateMethodsOrAccessors) {
        // Non-static private instance methods and accessors are gathered into descriptor
        // definitions for the shared private prototype descriptor (PRIVATE_PROTO).
        Node descriptorsLit = astFactory.createObjectLit();
        for (ClassRecord.PrivateMember pm : record.privateMembers) {
          // Process instance (non-static) private members.
          if (!pm.isStatic) {
            // Process private instance methods.
            if (pm.kind == ClassRecord.PrivateMemberKind.METHOD
                && pm.methodNode != null
                && pm.methodNode.hasChildren()) {
              rewriteSuperReferencesInPrivateMember(pm.methodNode, record);
              Node fnNode = pm.methodNode.getFirstChild().detach();
              pm.methodNode.detach();
              Node valProp = astFactory.createStringKey("value", fnNode);
              Node descriptorLit = astFactory.createObjectLit(valProp);
              Node memberKey = astFactory.createStringKey(pm.propertyName(), descriptorLit);
              descriptorsLit.addChildToBack(memberKey);
            } else if (pm.kind == ClassRecord.PrivateMemberKind.ACCESSOR) {
              // Process private instance accessors (getters/setters).
              Node descriptorLit = astFactory.createObjectLit();
              if (pm.getterNode != null && pm.getterNode.hasChildren()) {
                rewriteSuperReferencesInPrivateMember(pm.getterNode, record);
                Node getFn = pm.getterNode.getFirstChild().detach();
                pm.getterNode.detach();
                if (rewriteThisToThisDotSelf(getFn)) {
                  record.needsInstanceSelf = true;
                }
                Node getProp = astFactory.createStringKey("get", getFn);
                descriptorLit.addChildToBack(getProp);
              }
              if (pm.setterNode != null && pm.setterNode.hasChildren()) {
                rewriteSuperReferencesInPrivateMember(pm.setterNode, record);
                Node setFn = pm.setterNode.getFirstChild().detach();
                pm.setterNode.detach();
                if (rewriteThisToThisDotSelf(setFn)) {
                  record.needsInstanceSelf = true;
                }
                Node setProp = astFactory.createStringKey("set", setFn);
                descriptorLit.addChildToBack(setProp);
              }
              Node memberKey = astFactory.createStringKey(pm.propertyName(), descriptorLit);
              descriptorsLit.addChildToBack(memberKey);
            }
          }
        }

        // Generates: const PRIVATE_PROTO$uid = Object.create(null, { method: { value: function(...)
        // {} } });
        Node createProp =
            astFactory.createGetPropWithUnknownType(
                astFactory.createNameWithUnknownType("Object"), "create");
        Node protoCall =
            astFactory.createCallWithUnknownType(
                createProp, astFactory.createNull(), descriptorsLit);
        Node protoVar =
            astFactory
                .createSingleConstNameDeclaration(
                    record.getPrivateProtoVarName(compiler, t), protoCall)
                .srcrefTreeIfMissing(record.classNode);
        protoVar.insertBefore(classInsertionPoint);
        compiler.reportChangeToEnclosingScope(protoVar);
        t.reportCodeChange();
      }
    }
    // Create const STATIC_PRIVATE_MAP$uid = new $jscomp.PrivateMap() declaration for static private
    // members.
    if (record.hasStaticPrivateMembers) {
      compiler.getRuntimeJsLibManager().injectLibForField("$jscomp.PrivateMap");
      Node staticMapVar =
          astFactory
              .createSingleConstNameDeclaration(
                  record.getStaticPrivateMapVarName(compiler, t),
                  astFactory.createNewNode(astFactory.createQNameWithUnknownType(jscompPrivateMap)))
              .srcrefTreeIfMissing(record.classNode);
      staticMapVar.insertBefore(classInsertionPoint);
    }
  }

  private record ResolvedPrivateMember(
      ClassRecord classRecord, ClassRecord.PrivateMember privateMember) {}

  /**
   * Finds the private member declaration in the enclosing class stack by its name (including the
   * '#' prefix).
   */
  private @Nullable ResolvedPrivateMember findPrivateMember(String name) {
    for (ClassRecord record : classStack) {
      if (record.hasPrivateMember(name)) {
        return new ResolvedPrivateMember(record, record.getPrivateMember(name));
      }
    }
    return null;
  }

  /**
   * Rewrites private identifier brand checks (e.g. {@code #field in obj}) to use {@code
   * PRIVATE_MAP.has(obj)}.
   */
  private void rewritePrivateIn(NodeTraversal t, Node inNode) {
    checkArgument(inNode.isIn(), inNode);
    Node left = inNode.getFirstChild();
    String name = left.getString();
    ResolvedPrivateMember resolved = findPrivateMember(name);
    if (resolved == null) {
      maybeReportPrivatePropertiesCannotConvertYet(left);
      return;
    }

    Node right = inNode.getLastChild().detach();
    ClassRecord record = resolved.classRecord();
    boolean isStatic = resolved.privateMember().isStatic;
    String mapVarName =
        isStatic
            ? record.getStaticPrivateMapVarName(compiler, t)
            : record.getPrivateMapVarName(compiler, t);

    Node mapNameNode = astFactory.createNameWithUnknownType(mapVarName);
    Node hasCallee = astFactory.createGetPropWithUnknownType(mapNameNode, "has");
    Node hasCall = astFactory.createCallWithUnknownType(hasCallee, right);

    inNode.replaceWith(hasCall.srcrefTree(inNode));
    t.reportCodeChange();
  }

  /**
   * Rewrites private property accesses (e.g. {@code obj.#field}) to use {@code
   * PRIVATE_MAP.get(obj).field}.
   *
   * <p>For non-static private methods:
   *
   * <ul>
   *   <li>Direct calls: {@code obj.#method(args)} are rewritten to {@code
   *       PRIVATE_MAP.get(obj).method.call(obj, args)}.
   *   <li>Method access (tear-off): {@code obj.#method} is rewritten to {@code
   *       PRIVATE_MAP.get(obj).method}.
   * </ul>
   *
   * <p>TODO(b/236744850): Consider memoizing PRIVATE_MAP.get(obj) into a local temporary variable
   * when multiple private accesses occur on the same receiver within a single statement or method
   * scope to reduce WeakMap lookup overhead.
   */
  private void rewritePrivateGetProp(NodeTraversal t, Node getPropNode) {
    String name = getPropNode.getString();
    ResolvedPrivateMember resolved = findPrivateMember(name);
    if (resolved == null) {
      maybeReportPrivatePropertiesCannotConvertYet(getPropNode);
      return;
    }

    ClassRecord record = resolved.classRecord();
    ClassRecord.PrivateMember pm = resolved.privateMember();

    // Private methods are read-only and cannot be reassigned (e.g., `this.#method = fn`).
    // Report an error if a private method is used as an L-value.
    if (NodeUtil.isLValue(getPropNode) && pm.kind == ClassRecord.PrivateMemberKind.METHOD) {
      compiler.report(
          JSError.make(getPropNode, ILLEGAL_PRIVATE_MEMBER_ASSIGNMENT, pm.propertyName()));
      return;
    }

    Node parent = getPropNode.getParent();
    rewritePrivateMemberAccess(t, getPropNode, record, pm, parent);
  }

  /**
   * Rewrites a private member access or invocation.
   *
   * <p>Handles three primary cases:
   *
   * <ol>
   *   <li>Direct member calls with side-effecting receivers (e.g. {@code getObj()?.#method(a)} or
   *       {@code getObj()?.#field(a)}):
   *       <pre>{@code
   * let TMP;
   * (TMP = getObj(), TMP == null ? void 0 : PRIVATE_MAP.get(TMP).member.call(TMP, a))
   *
   * }</pre>
   *   <li>Direct member calls with side-effect-free receivers (e.g. {@code this.#method(a)} or
   *       {@code obj?.#field?.(a)}):
   *       <pre>{@code
   * obj == null ? void 0 : PRIVATE_MAP.get(obj).member.call(obj, a)
   *
   * }</pre>
   *   <li>Indirect reads, field accesses, and method tear-offs (e.g. {@code const fn =
   *       obj?.#method} or {@code obj?.#field}):
   *       <pre>{@code
   * const fn = obj == null ? void 0 : PRIVATE_MAP.get(obj).member;
   *
   * }</pre>
   * </ol>
   */
  private void rewritePrivateMemberAccess(
      NodeTraversal t,
      Node getPropNode,
      ClassRecord record,
      ClassRecord.PrivateMember pm,
      Node parent) {
    boolean isStatic = pm.isStatic;
    String mapVarName =
        isStatic
            ? record.getStaticPrivateMapVarName(compiler, t)
            : record.getPrivateMapVarName(compiler, t);
    String memberPropName = pm.propertyName();

    Node receiver = getPropNode.getFirstChild().detach();
    Node mapNameNode = astFactory.createNameWithUnknownType(mapVarName);
    Node getCallee = astFactory.createGetPropWithUnknownType(mapNameNode, "get");

    boolean isOptChain = getPropNode.isOptChainGetProp();
    Node endOfSegment = isOptChain ? NodeUtil.getEndOfOptChainSegment(getPropNode) : null;

    boolean isDirectCall =
        (parent.isCall() || parent.isOptChainCall())
            && Objects.equals(parent.getFirstChild(), getPropNode);

    if (isDirectCall) {
      boolean isOptionalCall = parent.isOptChainCall() && parent.isOptionalChainStart();

      parent.setIsOptionalChainStart(false);

      if (receiverNeedsTempVar(receiver)) {
        // If evaluating receiver twice could introduce side effects or alter execution state,
        // declare a temporary variable (e.g. `let TMP;`) and evaluate the call using a comma
        // expression:
        // `(TMP = receiver, PRIVATE_MAP.get(TMP).member.call(TMP, ...args))`
        String tempName = generateUniqueTmpVarName(t);
        Node insertionBlock = getDeclarationInsertionPoint(getPropNode, t);
        Node decl = astFactory.createSingleLetNameDeclaration(tempName);
        insertionBlock.addChildToFront(decl.srcrefTree(getPropNode));
        NodeUtil.addFeatureToScript(t.getCurrentScript(), Feature.LET_DECLARATIONS, compiler);

        Node tempNameNode1 = astFactory.createNameWithUnknownType(tempName).srcref(getPropNode);
        Node assign = astFactory.createAssign(tempNameNode1, receiver).srcref(getPropNode);
        receiver = astFactory.createNameWithUnknownType(tempName).srcref(getPropNode);

        Node tempNameNode2 = astFactory.createNameWithUnknownType(tempName).srcref(getPropNode);
        Node tempNameNode3 = astFactory.createNameWithUnknownType(tempName).srcref(getPropNode);

        Node getCall =
            astFactory.createCallWithUnknownType(getCallee, tempNameNode2).srcref(getPropNode);
        Node methodGetProp = astFactory.createGetPropWithUnknownType(getCall, memberPropName);
        Node callCallee = createCallCallee(methodGetProp, isOptionalCall, getPropNode);
        parent.setToken(callCallee.isOptChainGetProp() ? Token.OPTCHAIN_CALL : Token.CALL);

        callCallee.srcrefTreeIfMissing(getPropNode);
        tempNameNode3.srcrefTree(getPropNode);

        getPropNode.detach();
        parent.addChildToFront(callCallee);
        tempNameNode3.insertAfter(callCallee);

        Node resultExpr =
            wrapOptionalChainStartIfNecessary(receiver, parent, endOfSegment, isOptChain);
        Node placeholder = IR.empty();
        resultExpr.replaceWith(placeholder);
        Node comma = astFactory.createComma(assign, resultExpr).srcref(getPropNode);
        placeholder.replaceWith(comma);

        t.reportCodeChange();
      } else {
        // Direct private member call with a side-effect-free receiver (e.g. `this` or a simple
        // variable):
        // Rewritten to `PRIVATE_MAP.get(receiver).member.call(receiver, ...args)`.
        Node getCall = astFactory.createCallWithUnknownType(getCallee, receiver);
        Node methodGetProp = astFactory.createGetPropWithUnknownType(getCall, memberPropName);
        Node receiverArg = receiver.cloneTree();
        receiverArg.srcrefTree(getPropNode);

        getPropNode.detach();
        Node callCallee = createCallCallee(methodGetProp, isOptionalCall, getPropNode);
        parent.setToken(callCallee.isOptChainGetProp() ? Token.OPTCHAIN_CALL : Token.CALL);
        callCallee.srcrefTreeIfMissing(getPropNode);
        parent.addChildToFront(callCallee);
        receiverArg.insertAfter(callCallee);
        wrapOptionalChainStartIfNecessary(receiver, parent, endOfSegment, isOptChain);
        t.reportCodeChange();
      }
    } else {
      // Indirect read, field access, or method tear-off (e.g., `const fn = this.#method` or
      // `this.#field`):
      // Rewritten to `PRIVATE_MAP.get(receiver).propertyName`.
      Node assignComma = extractReceiverTmpIfNecessary(t, receiver, getPropNode, isOptChain);
      if (assignComma != null) {
        receiver = assignComma.getFirstChild().cloneTree();
      }
      Node getCall = astFactory.createCallWithUnknownType(getCallee, receiver);
      Node methodGetProp = astFactory.createGetPropWithUnknownType(getCall, memberPropName);
      getPropNode.replaceWith(methodGetProp.srcrefTree(getPropNode));
      Node result =
          wrapOptionalChainStartIfNecessary(receiver, methodGetProp, endOfSegment, isOptChain);

      if (assignComma != null) {
        Node placeholder = IR.empty();
        result.replaceWith(placeholder);
        Node comma = astFactory.createComma(assignComma, result).srcref(getPropNode);
        placeholder.replaceWith(comma);
      }

      t.reportCodeChange();
    }
  }

  /**
   * Extracts a temporary variable declaration for a side-effecting receiver in an optional chain.
   *
   * <p>For example, when transpiling:
   *
   * <pre>{@code
   * // JS input:
   * getObj()?.#field
   *
   * // Transpiled JS output:
   * let TMP;
   * (TMP = getObj(), TMP == null ? void 0 : PRIVATE_MAP.get(TMP).field)
   * }</pre>
   *
   * @return an assignment node {@code (TMP = receiver)} to prepend in a comma expression, or {@code
   *     null} if no temporary variable is needed.
   */
  private @Nullable Node extractReceiverTmpIfNecessary(
      NodeTraversal t, Node receiver, Node getPropNode, boolean isOptChain) {
    if (!isOptChain || !receiverNeedsTempVar(receiver)) {
      return null;
    }
    String tempName = generateUniqueTmpVarName(t);
    Node insertionBlock = getDeclarationInsertionPoint(getPropNode, t);
    Node decl = astFactory.createSingleLetNameDeclaration(tempName);
    insertionBlock.addChildToFront(decl.srcrefTree(getPropNode));
    NodeUtil.addFeatureToScript(t.getCurrentScript(), Feature.LET_DECLARATIONS, compiler);

    Node tempNameNode = astFactory.createNameWithUnknownType(tempName).srcref(getPropNode);
    return astFactory.createAssign(tempNameNode, receiver).srcref(getPropNode);
  }

  /**
   * Wraps an optional chained private member access with a nullish short-circuit check on the
   * receiver, climbing to the end of the current optional chain segment.
   *
   * <p>For example, transpiles:
   *
   * <pre>{@code
   * // Trailing property access in optional chain segment:
   * obj?.#field.prop
   * // -> obj == null ? void 0 : PRIVATE_MAP.get(obj).field.prop
   *
   * // Direct private method invocation:
   * obj?.#method(arg)
   * // -> obj == null ? void 0 : PRIVATE_MAP.get(obj).method.call(obj, arg)
   * }</pre>
   */
  @CanIgnoreReturnValue
  private Node wrapOptionalChainStartIfNecessary(
      Node receiver, Node accessExpr, @Nullable Node endOfSegment, boolean isOptChain) {
    if (!isOptChain) {
      return accessExpr;
    }
    Node segmentRoot =
        (endOfSegment != null && endOfSegment.getParent() != null) ? endOfSegment : accessExpr;
    if (!Objects.equals(segmentRoot, accessExpr)) {
      NodeUtil.convertToNonOptionalChainSegmentDownTo(segmentRoot, accessExpr);
    }

    Node placeholder = IR.empty();
    if (segmentRoot.getParent() != null) {
      segmentRoot.replaceWith(placeholder);
    }
    // We must short-circuit before calling PRIVATE_MAP.get(receiver), since PRIVATE_MAP.get throws
    // on nullish receivers.
    Node hook =
        astFactory
            .createOptionalChainShortCircuit(receiver.cloneTree(), segmentRoot)
            .srcrefTreeIfMissing(segmentRoot);
    if (placeholder.getParent() != null) {
      placeholder.replaceWith(hook);
    }
    Node hookParent = hook.getParent();
    if (hookParent != null && (hookParent.isCall() || hookParent.isOptChainCall())) {
      hook.setIsParenthesized(true);
      if (Objects.equals(hookParent.getFirstChild(), hook)) {
        hookParent.putBooleanProp(Node.FREE_CALL, true);
      }
    }
    return hook;
  }

  /**
   * Creates the {@code .call} property access node for a private method invocation.
   *
   * <p>If the invocation itself was optional (e.g. {@code obj.#method?.(arg)}), starts a new
   * optional chain segment ({@code .call?.(obj, arg)}). Otherwise creates a standard property
   * access {@code .call(obj, arg)}.
   */
  private Node createCallCallee(Node methodGetProp, boolean isOptionalCall, Node getPropNode) {
    if (isOptionalCall) {
      return astFactory.createStartOptChainGetprop(methodGetProp, "call", type(getPropNode));
    } else {
      return astFactory.createGetPropWithUnknownType(methodGetProp, "call");
    }
  }

  /**
   * Rewrites top-level {@code this} references inside a private accessor body to {@code
   * this.$self}.
   *
   * @return true if any {@code this} reference was rewritten.
   */
  @CanIgnoreReturnValue
  private boolean rewriteThisToThisDotSelf(Node fn) {
    Node fnBody = NodeUtil.getFunctionBody(fn);
    if (fnBody == null) {
      return false;
    }
    boolean[] hasThis = new boolean[1];
    NodeUtil.visitPostOrder(
        fnBody,
        (n) -> {
          if (n.isThis()) {
            hasThis[0] = true;
            Node target =
                astFactory
                    .createGetPropWithUnknownType(
                        astFactory.createThis(type(StandardColors.UNKNOWN)), "$self")
                    .srcref(n);
            n.replaceWith(target);
            compiler.reportChangeToEnclosingScope(target);
          }
        },
        (n) -> !n.isClass() && (!n.isFunction() || n.isArrowFunction()));
    return hasThis[0];
  }

  private boolean hasThisReference(Node fn) {
    Node fnBody = NodeUtil.getFunctionBody(fn);
    if (fnBody == null) {
      return false;
    }
    boolean[] hasThis = new boolean[1];
    NodeUtil.visitPostOrder(
        fnBody,
        (n) -> {
          if (n.isThis()) {
            hasThis[0] = true;
          }
        },
        (n) -> !n.isClass() && (!n.isFunction() || n.isArrowFunction()));
    return hasThis[0];
  }

  /**
   * Rewrites {@code super} references inside private methods or accessors into explicit target
   * calls or Reflect calls.
   *
   * <ul>
   *   <li>{@code super.method()} &rarr; {@code Base.method.call(this)}
   *   <li>{@code super.prop} &rarr; {@code Reflect.get(Base, JSCompiler_renameProperty('prop',
   *       Base), this)}
   *   <li>{@code super.prop = val} &rarr; {@code Reflect.set(Base,
   *       JSCompiler_renameProperty('prop', Base), val, this)}
   * </ul>
   */
  private void rewriteSuperReferencesInPrivateMember(Node memberNode, ClassRecord record) {
    if (record.normalizedNames.superClassNode().isEmpty()) {
      return;
    }
    Node fn = memberNode.getFirstChild();
    Node fnBody = NodeUtil.getFunctionBody(fn);
    if (fnBody == null || !NodeUtil.referencesSuper(fnBody)) {
      return;
    }

    boolean isStatic = memberNode.isStaticMember();
    NodeUtil.visitPostOrder(
        fnBody,
        (n) -> {
          if (n.isSuper()) {
            Node parent = n.getParent();
            if (parent.isGetProp() || parent.isGetElem()) {
              Node target;
              if (isStatic) {
                target = record.createNewSuperclassReferenceNode().srcrefTree(n);
              } else {
                // TODO(b/236744850): Consider emitting dynamic prototype chain lookups
                // (`Object.getPrototypeOf(Child.prototype).method`) rather than static prototype
                // accesses (`Base.prototype.method`) if dynamic prototype mutation must be
                // supported.
                target =
                    astFactory
                        .createPrototypeAccess(record.createNewSuperclassReferenceNode())
                        .srcrefTree(n);
              }

              Node grandParent = parent.getParent();
              if (grandParent != null
                  && grandParent.isCall()
                  && Objects.equals(grandParent.getFirstChild(), parent)) {
                // Method call: super.method(...)
                n.replaceWith(target);
                // Note: For instance super calls (`!isStatic`) or when static inheritance is
                // enabled
                // (`!getAssumeStaticInheritanceIsNotUsed()`), we invoke the method via
                // `.call(this)`
                // so the `this` receiver is preserved across the class hierarchy.
                if (!isStatic || !compiler.getOptions().getAssumeStaticInheritanceIsNotUsed()) {
                  Node callCallee =
                      astFactory.createGetPropWithUnknownType(parent.detach(), "call");
                  grandParent.addChildToFront(callCallee.srcrefTreeIfMissing(parent));
                  Node thisArg = astFactory.createThis(type(StandardColors.UNKNOWN)).srcref(n);
                  thisArg.insertAfter(callCallee);
                }
              } else if (grandParent != null
                  && grandParent.isAssign()
                  && Objects.equals(grandParent.getFirstChild(), parent)) {
                // Setter write: super.prop = value
                Node rhs = grandParent.getSecondChild().detach();
                Node propKey =
                    parent.isGetProp()
                        ? astFactory.createCall(
                            astFactory.createName(
                                NodeUtil.JSC_PROPERTY_NAME_FN, type(StandardColors.UNKNOWN)),
                            type(StandardColors.STRING),
                            astFactory.createString(parent.getString()),
                            record.createNewSuperclassReferenceNode().srcrefTree(n))
                        : parent.getSecondChild().detach();

                Node reflectSet =
                    astFactory.createCall(
                        astFactory.createGetPropWithUnknownType(
                            astFactory.createName("Reflect", type(StandardColors.UNKNOWN)), "set"),
                        type(StandardColors.UNKNOWN),
                        target,
                        propKey,
                        rhs,
                        astFactory.createThis(type(StandardColors.UNKNOWN)).srcref(n));
                grandParent.replaceWith(reflectSet.srcrefTreeIfMissing(grandParent));
              } else {
                // Getter read: super.prop
                Node propKey =
                    parent.isGetProp()
                        ? astFactory.createCall(
                            astFactory.createName(
                                NodeUtil.JSC_PROPERTY_NAME_FN, type(StandardColors.UNKNOWN)),
                            type(StandardColors.STRING),
                            astFactory.createString(parent.getString()),
                            record.createNewSuperclassReferenceNode().srcrefTree(n))
                        : parent.getSecondChild().detach();

                Node reflectGet =
                    astFactory.createCall(
                        astFactory.createGetPropWithUnknownType(
                            astFactory.createName("Reflect", type(StandardColors.UNKNOWN)), "get"),
                        type(StandardColors.UNKNOWN),
                        target,
                        propKey,
                        astFactory.createThis(type(StandardColors.UNKNOWN)).srcref(n));
                parent.replaceWith(reflectGet.srcrefTreeIfMissing(parent));
              }
              compiler.reportChangeToEnclosingScope(fnBody);
            }
          }
        },
        (n) -> !n.isClass());
  }

  /** Rewrites and moves all side effected computed field keys to the top */
  private void rewriteSideEffectedComputedProps(
      NodeTraversal t, ClassRecord record, Node insertionPoint) {
    Deque<Node> computedPropsWithSideEffects = record.computedPropsWithSideEffects;

    if (computedPropsWithSideEffects.isEmpty()) {
      return;
    }

    while (!computedPropsWithSideEffects.isEmpty()) {
      Node computedPropMember = computedPropsWithSideEffects.remove();
      extractExpressionFromCompField(t, record, computedPropMember, insertionPoint);
    }
    t.reportCodeChange();
  }

  /**
   * Extracts the expression in the LHS of a computed field to not disturb possible side effects and
   * allow for this and super to be used in the LHS of a computed field in certain cases. Does not
   * extract a computed field that was already moved into a computed function.
   *
   * <p>E.g.
   *
   * <pre>
   * class Foo {
   *   [bar('str')] = 4;
   * }
   * </pre>
   *
   * becomes
   *
   * <pre>
   * var $jscomp$computedfield$0 = bar('str');
   * class Foo {
   *   [$jscomp$computedfield$0] = 4;
   * }
   * </pre>
   */
  private void extractExpressionFromCompField(
      NodeTraversal t, ClassRecord record, Node memberField, Node insertionPoint) {
    checkArgument(memberField.isComputedFieldDef() || memberField.isComputedProp(), memberField);

    Node compExpression = memberField.removeFirstChild();
    Node compFieldVar =
        astFactory
            .createSingleVarNameDeclaration(generateUniqueCompFieldVarName(t), compExpression)
            .srcrefTreeIfMissing(record.classNode);
    Node compFieldName = compFieldVar.getFirstChild();
    memberField.addChildToFront(compFieldName.cloneNode());
    compFieldVar.insertBefore(insertionPoint);
    compFieldVar.srcrefTreeIfMissing(record.classNode);
  }

  /**
   * Rewrites and moves all instance fields into the constructor.
   *
   * <p>E.g.
   *
   * <pre>
   * class Foo {
   *   field = 1;
   *   #privField = 2;
   * }
   * </pre>
   *
   * becomes
   *
   * <pre>
   * class Foo {
   *   constructor() {
   *     const PRIVATE$uid = {};
   *     PRIVATE$uid.$self = this;
   *     PRIVATE_MAP$uid.set(this, PRIVATE$uid);
   *     PRIVATE$uid.privField = 2;
   *     this.field = 1;
   *   }
   * }
   * </pre>
   */
  private void rewriteInstanceMembers(NodeTraversal t, ClassRecord record) {
    Deque<Node> instanceMembers = record.instanceMembers;
    boolean hasPriv = transpilePrivateClassFields && record.hasInstancePrivateMembers;

    if (instanceMembers.isEmpty() && !hasPriv) {
      return;
    }
    ctorCreator.synthesizeClassConstructorIfMissing(t, record.classNode);
    Node ctor = NodeUtil.getEs6ClassConstructorMemberFunctionDef(record.classNode);
    Node ctorBlock = ctor.getFirstChild().getLastChild();
    Node insertionPoint = addTemporaryInsertionPoint(ctorBlock, record);

    if (hasPriv) {
      String mapName = record.getPrivateMapVarName(compiler, t);
      String privName = record.getPrivateVarName(compiler, t);

      Node privInit;
      if (record.hasInstancePrivateMethodsOrAccessors) {
        // Initializer: Object.create(PRIVATE_PROTO$uid)
        Node protoName =
            astFactory.createNameWithUnknownType(record.getPrivateProtoVarName(compiler, t));
        Node createProp =
            astFactory.createGetPropWithUnknownType(
                astFactory.createNameWithUnknownType("Object"), "create");
        privInit = astFactory.createCallWithUnknownType(createProp, protoName);
      } else {
        // Initializer: Object.create(null)
        Node createProp =
            astFactory.createGetPropWithUnknownType(
                astFactory.createNameWithUnknownType("Object"), "create");
        privInit = astFactory.createCallWithUnknownType(createProp, astFactory.createNull());
      }
      // Add `const PRIVATE$uid = privInit;` to the original code.
      Node privDecl =
          astFactory
              .createSingleConstNameDeclaration(privName, privInit)
              .srcrefTreeIfMissing(record.classNode);
      privDecl.insertBefore(insertionPoint);

      if (record.needsInstanceSelf) {
        // Add `PRIVATE$uid.$self = this;` to the original code.
        Node privSelf =
            astFactory.createGetPropWithUnknownType(
                astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)), "$self");
        Node assignSelf =
            astFactory
                .createAssignStatement(privSelf, astFactory.createThisForEs6Class(record.classNode))
                .srcrefTreeIfMissing(record.classNode);
        assignSelf.insertBefore(insertionPoint);
      }

      // Add `PRIVATE_MAP$uid.set(this, PRIVATE$uid);` to the original code.
      Node mapNameNode = astFactory.createNameWithUnknownType(mapName);
      Node mapSetCallee = astFactory.createGetPropWithUnknownType(mapNameNode, "set");
      Node mapSetCall =
          astFactory.createCallWithUnknownType(
              mapSetCallee,
              astFactory.createThisForEs6Class(record.classNode),
              astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)));
      Node mapSetStmt = astFactory.exprResult(mapSetCall).srcrefTreeIfMissing(record.classNode);
      mapSetStmt.insertBefore(insertionPoint);
    }

    while (!instanceMembers.isEmpty()) {
      Node instanceMember = instanceMembers.remove();
      checkState(
          instanceMember.isMemberFieldDef() || instanceMember.isComputedFieldDef(), instanceMember);

      if (instanceMember.isPrivateIdentifier()) {
        if (transpilePrivateClassFields) {
          String privName = record.getPrivateVarName(compiler, t);
          String propName = instanceMember.getString().substring(1);
          // Add `PRIVATE$uid.field = fieldValue;` to the original code.
          Node lhs =
              astFactory.createGetPropWithUnknownType(
                  astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)), propName);
          Node fieldValue =
              instanceMember.hasChildren()
                  ? instanceMember.removeFirstChild()
                  : astFactory.createUndefinedValue();
          Node assign = astFactory.createAssignStatement(lhs, fieldValue);
          assign.srcrefTreeIfMissing(instanceMember);
          assign.insertBefore(insertionPoint);
          instanceMember.detach();
        }
      } else {
        // Add `this.field = fieldValue;` or `this[field] = fieldValue;` to the original code.
        Node thisNode = astFactory.createThisForEs6ClassMember(instanceMember);
        Node transpiledNode =
            instanceMember.isMemberFieldDef()
                ? convNonCompFieldToGetProp(thisNode, instanceMember, /* isStatic= */ false)
                : convCompFieldToGetElem(thisNode, instanceMember, /* isStatic= */ false);

        if (transpiledNode != null) {
          transpiledNode.insertBefore(insertionPoint);
        }
      }
    }

    if (transpilePrivateClassFields) {
      // Remove original non-static private member declaration nodes (fields and methods) from the
      // class body AST now that their transpiled equivalents (e.g., constructor initializations,
      // PRIVATE_PROTO descriptors) have been generated.
      for (ClassRecord.PrivateMember pm : record.privateMembers) {
        if (!pm.isStatic) {
          for (Node declNode : pm.declarationNodes) {
            if (declNode.getParent() != null) {
              NodeUtil.deleteNode(declNode, compiler);
            }
          }
        }
      }
    }

    insertionPoint.detach();

    // We moved the field from the class body to the constructor, so we need both.
    t.reportCodeChange();
    t.reportCodeChange(ctorBlock);
  }

  /**
   * Finds the location of super() call in the constructor and add a temporary empty node after the
   * super() call. If there is no super() call, add a temporary empty node at the beginning of the
   * constructor body after all function declarations.
   *
   * <p>Returns the added temporary empty node
   */
  private Node addTemporaryInsertionPoint(Node ctorBlock, ClassRecord classRecord) {
    checkState(
        classRecord.superCalls.size() <= 1,
        "classes with public fields must have only one super() call at the constructor root: %s",
        classRecord.classNode);

    Node tempNode = IR.empty();
    if (classRecord.superCalls.size() == 1) {
      Node stmt = ensureSuperCallIsOwnStatement(classRecord.superCalls.get(0));
      tempNode.insertAfter(stmt);
      return tempNode;
    }
    // Search for super() calls added by SynthesizeExplicitConstructors.
    for (Node stmt = ctorBlock.getFirstChild(); stmt != null; stmt = stmt.getNext()) {
      if (NodeUtil.isExprCall(stmt) && stmt.getFirstFirstChild().isSuper()) {
        tempNode.insertAfter(stmt);
        return tempNode;
      }
    }
    Node insertionPoint = NodeUtil.getInsertionPointAfterAllInnerFunctionDeclarations(ctorBlock);
    if (insertionPoint != null) {
      tempNode.insertBefore(insertionPoint);
    } else {
      // functionBody only contains hoisted function declarations
      ctorBlock.addChildToBack(tempNode);
    }
    return tempNode;
  }

  /**
   * Returns a statement containing either {@code super(...);} or {@code var tmp = super(...)},
   * extracting the given super call into a {@code tmp} variable if necessary.
   */
  private Node ensureSuperCallIsOwnStatement(Node superCall) {
    Node parent = superCall.getParent();
    if (parent.isExprResult()) {
      return parent; // No extraction needed.
    }
    checkState(
        expressionDecomposer.canExposeExpression(superCall) != DecompositionType.UNDECOMPOSABLE,
        "Cannot decompose super() call in a class with class fields. Move super() call to the"
            + " root of the constructor. %s",
        superCall);
    expressionDecomposer.maybeExposeExpression(superCall);
    expressionDecomposer.moveExpression(superCall);
    return NodeUtil.getEnclosingStatement(superCall);
  }

  /**
   * Reports that transpilation of private class properties is not yet supported when attempting to
   * rewrite or normalize private identifiers. See b/236744850.
   */
  private void maybeReportPrivatePropertiesCannotConvertYet(Node n) {
    if (transpilePrivateClassFields && n.isPrivateIdentifier()) {
      TranspilationUtil.cannotConvertYet(compiler, n, "Private elements");
    }
  }

  /**
   * Creates a node that represents receiver.key = value; where the key and value comes from the
   * non-computed field
   */
  private @Nullable Node convNonCompFieldToGetProp(
      Node receiver, Node noncomputedField, boolean isStatic) {
    checkArgument(noncomputedField.isMemberFieldDef());
    checkArgument(receiver.getParent() == null, receiver);

    Node fieldValue = null;
    // We always move out the static field initialization.
    if (isStatic || transpileClassFields) {
      fieldValue = noncomputedField.getFirstChild();
    }

    return createFieldAssignment(
        noncomputedField,
        fieldValue,
        () ->
            astFactory.createGetProp(
                receiver, noncomputedField.getString(), type(noncomputedField)));
  }

  /**
   * Creates a node that represents receiver[key] = value; where the key and value comes from the
   * computed field
   */
  private @Nullable Node convCompFieldToGetElem(
      Node receiver, Node computedField, boolean isStatic) {
    checkArgument(computedField.isComputedFieldDef(), computedField);
    checkArgument(receiver.getParent() == null, receiver);

    Node fieldValue = null;
    if (computedField.getChildCount() == 2 && (isStatic || transpileClassFields)) {
      fieldValue = computedField.getLastChild();
    }

    return createFieldAssignment(
        computedField,
        fieldValue,
        () -> {
          Node compFieldNameExpr;
          if (transpileClassFields) {
            compFieldNameExpr = computedField.removeFirstChild();
          } else {
            compFieldNameExpr = computedField.getFirstChild().cloneTree();
          }
          return astFactory.createGetElem(receiver, compFieldNameExpr);
        });
  }

  /**
   * Shared helper to create an assignment statement for a class field. Handles logic for creating
   * undefined values for uninitialized fields during transpilation, as well as JSDoc transfer and
   * source reference mapping.
   */
  private @Nullable Node createFieldAssignment(
      Node field, @Nullable Node fieldValue, Supplier<Node> createAssignLhs) {
    // For public fields, we don't need to keep around the field declaration.
    // For private fields, we still need to keep them in the class body due to syntax requirements.
    if (transpileClassFields && !field.isPrivateIdentifier()) {
      field.detach();
    }

    // We don't make a copy of the static field declaration if it doesn't have an initializer and
    // we're not transpiling class fields.
    if (fieldValue == null) {
      if (!transpileClassFields) {
        return null;
      }

      // If we are transpiling class fields, we want an explicit undefined value so we properly
      // initialize the field.
      fieldValue = astFactory.createUndefinedValue();
    } else {
      // We are going to move fieldValue to a new parent, so detach it now.
      // (TODO: b/236744850): for private fields, consider keeping the initializers in the class
      // body.
      fieldValue.detach();
    }

    Node result = astFactory.createAssignStatement(createAssignLhs.get(), fieldValue);

    if (transpileClassFields) {
      // Move any JSDoc from the field declaration to the child of the EXPR_RESULT, which represents
      // the new declaration.
      // field is already detached, so there's no benefit to calling
      // NodeUtil.getBestJSDocInfo(field). For now at least, the JSDocInfo we want will always be
      // directly on field in all cases.
      result.getFirstChild().setJSDocInfo(field.getJSDocInfo());
    }
    result.srcrefTreeIfMissing(field);
    return result;
  }

  /** Rewrites and moves all static blocks and fields */
  private void rewriteStaticMembers(NodeTraversal t, ClassRecord record, Node insertionPoint) {
    Deque<Node> staticMembers = record.staticMembers;
    boolean hasPriv = transpilePrivateClassFields && record.hasStaticPrivateMembers;
    if (staticMembers.isEmpty() && !hasPriv) {
      return;
    }

    Node staticInitTempParent = IR.block();

    if (hasPriv) {
      String staticMapName = record.getStaticPrivateMapVarName(compiler, t);
      String privName = record.getStaticPrivateVarName(compiler, t);

      // Pre-scan static private accessors to check if any getter/setter references 'this'.
      // If so, we must set $self on the static private object.
      for (ClassRecord.PrivateMember pm : record.privateMembers) {
        if (pm.isStatic && pm.kind == ClassRecord.PrivateMemberKind.ACCESSOR) {
          if (pm.getterNode != null
              && pm.getterNode.hasChildren()
              && hasThisReference(pm.getterNode.getFirstChild())) {
            record.needsStaticSelf = true;
          }
          if (pm.setterNode != null
              && pm.setterNode.hasChildren()
              && hasThisReference(pm.setterNode.getFirstChild())) {
            record.needsStaticSelf = true;
          }
        }
      }

      // Add `const PRIVATE$uid = Object.create(null);` to the original code.
      Node createProp =
          astFactory.createGetPropWithUnknownType(
              astFactory.createNameWithUnknownType("Object"), "create");
      Node staticPrivInit =
          astFactory.createCallWithUnknownType(createProp, astFactory.createNull());
      Node privDecl =
          astFactory
              .createSingleConstNameDeclaration(privName, staticPrivInit)
              .srcrefTreeIfMissing(record.classNode);
      staticInitTempParent.addChildToBack(privDecl);

      if (record.needsStaticSelf) {
        // Add `PRIVATE$uid.$self = ClassName;` to the original code.
        Node privSelf =
            astFactory.createGetPropWithUnknownType(
                astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)), "$self");
        Node assignSelf =
            astFactory
                .createAssignStatement(
                    privSelf,
                    record.createNewNameReferenceNode().srcrefTreeIfMissing(record.classNode))
                .srcrefTreeIfMissing(record.classNode);
        staticInitTempParent.addChildToBack(assignSelf);
      }

      // Add `STATIC_PRIVATE_MAP$uid.set(ClassName, PRIVATE$uid);` to the original code.
      Node mapNameNode = astFactory.createNameWithUnknownType(staticMapName);
      Node mapSetCallee = astFactory.createGetPropWithUnknownType(mapNameNode, "set");
      Node mapSetCall =
          astFactory.createCallWithUnknownType(
              mapSetCallee,
              record.createNewNameReferenceNode().srcrefTreeIfMissing(record.classNode),
              astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)));
      Node mapSetStmt = astFactory.exprResult(mapSetCall).srcrefTreeIfMissing(record.classNode);
      staticInitTempParent.addChildToBack(mapSetStmt);

      addStaticPrivateMembers(record, privName, staticInitTempParent);
    }

    while (!staticMembers.isEmpty()) {
      Node staticMember = staticMembers.remove();
      if (staticMember.isPrivateIdentifier()) {
        if (transpilePrivateClassFields) {
          String privName = record.getStaticPrivateVarName(compiler, t);
          String propName = staticMember.getString().substring(1);
          // Add `PRIVATE$uid.staticField = fieldValue;` to the original code.
          Node lhs =
              astFactory.createGetPropWithUnknownType(
                  astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)), propName);
          Node fieldValue =
              staticMember.hasChildren()
                  ? staticMember.removeFirstChild()
                  : astFactory.createUndefinedValue();
          Node assign = astFactory.createAssignStatement(lhs, fieldValue);
          assign.srcrefTreeIfMissing(staticMember);
          staticInitTempParent.addChildToBack(assign);
          staticMember.detach();
        }
      } else {
        // if the name is a property access, we want the whole chain of accesses, while for other
        // cases we only want the name node
        Node nameToUse = record.createNewNameReferenceNode().srcrefTree(staticMember);

        Node transpiledNode =
            switch (staticMember.getToken()) {
              case BLOCK -> {
                Node block = staticMember.detach();
                t.reportCodeChange();
                // We ignore empty static initialization blocks.
                yield block.hasChildren() ? block : null;
              }
              case MEMBER_FIELD_DEF ->
                  convNonCompFieldToGetProp(nameToUse, staticMember, /* isStatic= */ true);
              case COMPUTED_FIELD_DEF ->
                  convCompFieldToGetElem(nameToUse, staticMember, /* isStatic= */ true);
              default -> throw new IllegalStateException(String.valueOf(staticMember));
            };
        if (transpiledNode != null) {
          staticInitTempParent.addChildToBack(transpiledNode);
        }
      }
    }

    if (transpilePrivateClassFields) {
      // Remove original static private member declaration nodes (fields and methods) from the class
      // body AST now that their transpiled equivalents (e.g. static initialization statements) have
      // been generated, preventing duplicate declarations in downstream compiler passes.
      for (ClassRecord.PrivateMember pm : record.privateMembers) {
        if (pm.isStatic) {
          for (Node declNode : pm.declarationNodes) {
            if (declNode.getParent() != null) {
              NodeUtil.deleteNode(declNode, compiler);
            }
          }
        }
      }
    }

    // If there is no static initialization logic, we are done.
    if (!staticInitTempParent.hasChildren()) {
      return;
    }

    // If there are no super references or private field references, place all the static
    // initialization code after the class.
    if (!hasPriv
        && !NodeUtil.has(
            staticInitTempParent,
            /* pred= */ (n) -> n.isSuper() || n.isPrivateIdentifier(),
            /* traverseChildrenPred= */ (n) ->
                !n.isClass() && (!n.isFunction() || n.isArrowFunction()))) {
      while (staticInitTempParent.hasChildren()) {
        staticInitTempParent.getLastChild().detach().insertAfter(insertionPoint);
      }
      t.reportCodeChange(insertionPoint.getParent());
      return;
    }

    // We will introduce a new static method and a call to it to contain static initialization code.

    // Add new static method "$jscomp$staticInit$[FILE_ID]$[number]".
    // All the static initialization logic goes into this method. We need a static method as opposed
    // to doing this logic alongside the class because #private members can only be accessed within
    // the class.
    String staticInitMethodName = generateUniqueStaticInitMethodName(t);
    Node staticInitMethodFunc =
        astFactory.createEmptyFunction(type(JSTypeNative.FUNCTION_TYPE, StandardColors.TOP_OBJECT));
    Node staticInitMethod =
        astFactory.createMemberFunctionDef(staticInitMethodName, staticInitMethodFunc);
    staticInitMethod.setStaticMember(true);

    Node staticInitBlock = staticInitMethod.getFirstChild().getLastChild();
    staticInitBlock.addChildrenToFront(staticInitTempParent.removeChildren());

    Node classMembers = NodeUtil.getClassMembers(record.classNode);
    staticInitMethod.srcrefTreeIfMissing(classMembers);
    classMembers.addChildToBack(staticInitMethod);
    compiler.reportChangeToChangeScope(staticInitMethodFunc);
    t.reportCodeChange(staticInitMethod);
    // Record the feature corresponding to a static method.
    NodeUtil.addFeatureToScript(t.getCurrentScript(), Feature.MEMBER_DECLARATIONS, compiler);

    // Add a call to the static initialization method after the class definition.
    Node staticInitCall =
        astFactory
            .createCall(
                astFactory.createGetProp(
                    record.createNewNameReferenceNode(),
                    staticInitMethodName,
                    type(staticInitMethodFunc)),
                type(JSTypeNative.VOID_TYPE, StandardColors.NULL_OR_VOID))
            .srcrefTreeIfMissing(classMembers);
    Node staticInitCallStmt = astFactory.exprResult(staticInitCall);
    staticInitCallStmt.insertAfter(insertionPoint);
  }

  /** Attaches static private methods and accessors to the static private object. */
  private void addStaticPrivateMembers(
      ClassRecord record, String privName, Node staticInitTempParent) {
    for (ClassRecord.PrivateMember pm : record.privateMembers) {
      // Only process static private members for static initialization.
      if (pm.isStatic) {
        // Assign static private method definitions to the static private object (e.g.,
        // PRIVATE$uid.method = function() {}).
        if (pm.kind == ClassRecord.PrivateMemberKind.METHOD
            && pm.methodNode != null
            && pm.methodNode.hasChildren()) {
          rewriteSuperReferencesInPrivateMember(pm.methodNode, record);
          Node fnNode = pm.methodNode.getFirstChild().detach();
          pm.methodNode.detach();
          Node lhs =
              astFactory.createGetPropWithUnknownType(
                  astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)),
                  pm.propertyName());
          Node assign = astFactory.createAssignStatement(lhs, fnNode);
          assign.srcrefTreeIfMissing(pm.methodNode);
          staticInitTempParent.addChildToBack(assign);
        } else if (pm.kind == ClassRecord.PrivateMemberKind.ACCESSOR) {
          // Assign static private accessor definitions to the static private object via
          // Object.defineProperty.
          Node descriptorLit = astFactory.createObjectLit();
          if (pm.getterNode != null && pm.getterNode.hasChildren()) {
            rewriteSuperReferencesInPrivateMember(pm.getterNode, record);
            Node getFn = pm.getterNode.getFirstChild().detach();
            pm.getterNode.detach();
            rewriteThisToThisDotSelf(getFn);
            descriptorLit.addChildToBack(astFactory.createStringKey("get", getFn));
          }
          if (pm.setterNode != null && pm.setterNode.hasChildren()) {
            rewriteSuperReferencesInPrivateMember(pm.setterNode, record);
            Node setFn = pm.setterNode.getFirstChild().detach();
            pm.setterNode.detach();
            rewriteThisToThisDotSelf(setFn);
            descriptorLit.addChildToBack(astFactory.createStringKey("set", setFn));
          }
          Node defineProp =
              astFactory.createGetPropWithUnknownType(
                  astFactory.createNameWithUnknownType("Object"), "defineProperty");
          Node call =
              astFactory.createCallWithUnknownType(
                  defineProp,
                  astFactory.createConstantName(privName, type(StandardColors.UNKNOWN)),
                  astFactory.createString(pm.propertyName()),
                  descriptorLit);
          Node declNode = pm.getPrimaryDeclarationNode();
          Node exprResult = astFactory.exprResult(call);
          if (declNode != null) {
            exprResult.srcrefTreeIfMissing(declNode);
          }
          staticInitTempParent.addChildToBack(exprResult);
        }
      }
    }
  }

  private void maybeUpdateClassSelfRef(NodeTraversal t, Node nameNode) {
    for (ClassRecord klass : classStack) {
      if (klass.bindingIdentifier.isEmpty()) {
        continue;
      }

      Node bindingIdentifier = klass.bindingIdentifier.get();
      if (
      // Skip if the inner class name is the same as the class name (either this is a class
      // declaration or the outer and inner class names are the same).
      bindingIdentifier.matchesName(klass.normalizedNames.classNameNode)
          // Skip if this IS the inner class name node (removed later when we visit the class).
          || nameNode == bindingIdentifier
          // Skip if this nameNode is not equal to the inner class name.
          || !nameNode.matchesQualifiedName(bindingIdentifier)) {
        continue;
      }

      // Ensure that this nameNode is not being shadowed by a different variable with the same name
      // as the inner class name.
      Var var = t.getScope().getVar(nameNode.getString());
      if (var == null || var.getNameNode() != bindingIdentifier) {
        continue;
      }

      Node newNameNode = klass.createNewNameReferenceNode().srcref(nameNode);
      nameNode.replaceWith(newNameNode);
      compiler.reportChangeToEnclosingScope(newNameNode);

      return; // We made the replacement so bail.
    }
  }

  /**
   * Visits {@code this} and {@code super} nodes in the class. Only makes changes in static contexts
   * and records super calls in the constructor for later.
   *
   * <p>For static {@code this}, we can only replace with the class name if in a static
   * initialization context (i.e. in a static field initializer or a static block).
   *
   * <p>For static {@code super}, we can always replace with the extended class name.
   *
   * <p>Note: This runs before {@link #rewriteStaticMembers} so the static members are still there.
   */
  private void visitThisAndSuper(NodeTraversal t, Node n) {
    if (isSuperCall(n.getParent())) {
      // super(...); calls are only legal in a constructor so we don't need to check for static
      // context.
      ClassRecord classRecord = classStack.peek();
      classRecord.superCalls.add(n.getParent());
      return;
    }
    Node rootNode = t.getClosestScopeRootNodeBindingThisOrSuper();
    Node rootParent = rootNode.getParent();
    if (rootNode.isFunction()
        && (rootParent.isMemberFunctionDef()
            || rootParent.isComputedProp()
            || rootParent.isGetterDef()
            || rootParent.isSetterDef())) {
      rootNode = rootParent;
    }
    boolean inStaticBlock = rootNode.isBlock() && rootNode.getParent().isClassMembers();
    if (!rootNode.isStaticMember() && !inStaticBlock) {
      return;
    }

    // We always rewrite static this to the class name in a static initialization context so that we
    // can normalize-away static initialization from field initializers and static blocks.
    boolean forceRewriteStaticThis = n.isThis() && isInStaticInitializationContext(rootNode);

    if (!doStaticInheritanceRewrites && !forceRewriteStaticThis) {
      return;
    }

    Node classNode = rootNode.getGrandparent();
    ClassRecord classRecord = classStack.peek();
    checkState(
        classRecord.classNode == classNode,
        "wrong class node: %s != %s",
        classRecord.classNode,
        classNode);

    Node newNameNode = null;
    if (forceRewriteStaticThis) {
      // For static this, we can only universally replace with the class name in a static
      // initialization context.
      newNameNode = classRecord.createNewNameReferenceNode().srcrefTree(n);
    } else if (doStaticSuperRewrites && n.isSuper()) {
      // For a static super, we can always rewrite the super as something else.
      newNameNode = classRecord.createNewSuperclassReferenceNode();
    }

    if (newNameNode != null) {
      String originalName = checkNotNull(n.getQualifiedName());
      newNameNode.srcrefTree(n).setOriginalName(originalName);
      n.replaceWith(newNameNode);
      t.reportCodeChange(newNameNode);
    }
  }

  private static boolean isSuperCall(Node n) {
    return n.isCall() && n.getFirstChild().isSuper();
  }

  // Note: Assumes that we have already filtered out non-static members and non-static blocks.
  private static boolean isInStaticInitializationContext(Node rootNode) {
    return switch (rootNode.getToken()) {
      case MEMBER_FUNCTION_DEF, COMPUTED_PROP, GETTER_DEF, SETTER_DEF -> {
        checkState(rootNode.isStaticMember());
        yield false;
      }
      case MEMBER_FIELD_DEF, COMPUTED_FIELD_DEF -> {
        checkState(rootNode.isStaticMember());
        yield true;
      }
      case BLOCK -> {
        checkState(rootNode.getParent().isClassMembers());
        yield true;
      }
      default -> throw new IllegalArgumentException("invalid root " + rootNode);
    };
  }

  private static class ClassRecord {
    static enum PrivateMemberKind {
      FIELD,
      METHOD,
      ACCESSOR,
    }

    /** Information about a private member declaration in the class. */
    static class PrivateMember {
      final String name;
      final PrivateMemberKind kind;
      final boolean isStatic;

      @Nullable Node methodNode;
      @Nullable Node getterNode;
      @Nullable Node setterNode;

      final List<Node> declarationNodes = new ArrayList<>();

      PrivateMember(String name, PrivateMemberKind kind, boolean isStatic, Node initialNode) {
        this.name = name;
        this.kind = kind;
        this.isStatic = isStatic;
        this.declarationNodes.add(initialNode);
        if (kind == PrivateMemberKind.METHOD) {
          this.methodNode = initialNode;
        } else if (initialNode.isGetterDef()) {
          this.getterNode = initialNode;
        } else if (initialNode.isSetterDef()) {
          this.setterNode = initialNode;
        }
      }

      String propertyName() {
        return name.startsWith("#") ? name.substring(1) : name;
      }

      /**
       * Returns the primary AST declaration node for source reference mapping, prioritizing getter,
       * then setter, then the first declaration node.
       */
      @Nullable Node getPrimaryDeclarationNode() {
        if (getterNode != null) {
          return getterNode;
        }
        if (setterNode != null) {
          return setterNode;
        }
        return Iterables.getFirst(declarationNodes, null);
      }
    }

    /** List of all private members declared in the class. */
    final List<PrivateMember> privateMembers = new ArrayList<>();

    /** Map of private member names (with '#' prefix) to their declarations. */
    final Map<String, PrivateMember> privateMembersByName = new LinkedHashMap<>();

    /** Name of the unique PrivateMap variable for instance private fields. */
    private String privateMapVarName = null;

    /** Name of the unique PrivateMap variable for static private fields. */
    private String staticPrivateMapVarName = null;

    /** Whether the class has any instance private members. */
    boolean hasInstancePrivateMembers = false;

    /** Whether the class has any instance private methods or accessors. */
    boolean hasInstancePrivateMethodsOrAccessors = false;

    /** Whether the class has any static private members. */
    boolean hasStaticPrivateMembers = false;

    /** Whether any instance private accessor body references top-level `this`. */
    boolean needsInstanceSelf = false;

    /** Whether any static private accessor body references top-level `this`. */
    boolean needsStaticSelf = false;

    void recordPrivateMember(Node n) {
      checkArgument(n.isPrivateIdentifier());
      String name =
          n.hasChildren() && n.getFirstChild().isName()
              ? n.getFirstChild().getString()
              : n.getString();
      checkArgument(name.startsWith("#"), name);
      boolean isStatic = n.isStaticMember();

      PrivateMemberKind kind;
      if (n.isMemberFieldDef() || n.isComputedFieldDef()) {
        kind = PrivateMemberKind.FIELD;
      } else if (n.isMemberFunctionDef()) {
        kind = PrivateMemberKind.METHOD;
      } else if (n.isGetterDef() || n.isSetterDef()) {
        kind = PrivateMemberKind.ACCESSOR;
      } else {
        throw new IllegalStateException("Unexpected node for private member: " + n);
      }

      PrivateMember pm;
      if (privateMembersByName.containsKey(name)) {
        pm = privateMembersByName.get(name);
        pm.declarationNodes.add(n);
        if (n.isGetterDef()) {
          pm.getterNode = n;
        } else if (n.isSetterDef()) {
          pm.setterNode = n;
        }
      } else {
        pm = new PrivateMember(name, kind, isStatic, n);
        privateMembers.add(pm);
        privateMembersByName.put(name, pm);
      }

      if ((kind == PrivateMemberKind.METHOD || kind == PrivateMemberKind.ACCESSOR) && !isStatic) {
        hasInstancePrivateMethodsOrAccessors = true;
      }

      if (isStatic) {
        hasStaticPrivateMembers = true;
      } else {
        hasInstancePrivateMembers = true;
      }
    }

    boolean hasPrivateMember(String name) {
      return privateMembersByName.containsKey(name);
    }

    PrivateMember getPrivateMember(String name) {
      return privateMembersByName.get(name);
    }

    private String privateVarName = null;
    private String staticPrivateVarName = null;
    private String privateProtoVarName = null;

    String getPrivateMapVarName(AbstractCompiler compiler, NodeTraversal t) {
      if (privateMapVarName == null) {
        privateMapVarName = generateUniquePrivateMapVarName(compiler, t);
      }
      return privateMapVarName;
    }

    String getPrivateProtoVarName(AbstractCompiler compiler, NodeTraversal t) {
      if (privateProtoVarName == null) {
        privateProtoVarName = generateUniquePrivateProtoVarName(compiler, t);
      }
      return privateProtoVarName;
    }

    String getStaticPrivateMapVarName(AbstractCompiler compiler, NodeTraversal t) {
      if (staticPrivateMapVarName == null) {
        staticPrivateMapVarName = generateUniqueStaticPrivateMapVarName(compiler, t);
      }
      return staticPrivateMapVarName;
    }

    String getPrivateVarName(AbstractCompiler compiler, NodeTraversal t) {
      if (privateVarName == null) {
        privateVarName = generateUniquePrivateVarName(compiler, t);
      }
      return privateVarName;
    }

    String getStaticPrivateVarName(AbstractCompiler compiler, NodeTraversal t) {
      if (staticPrivateVarName == null) {
        staticPrivateVarName = generateUniquePrivateVarName(compiler, t);
      }
      return staticPrivateVarName;
    }

    /**
     * The binding identifier (a.k.a. name node) of the class itself.
     *
     * <p>The node for {@code C} as in:
     *
     * <ul>
     *   <li>{@code class C {}}
     *   <li>{@code const D = class C {};} // Inner name node in this case.
     * </ul>
     *
     * <p>Absent as in:
     *
     * <ul>
     *   <li>{@code const C = class {};}
     * </ul>
     */
    final Optional<Node> bindingIdentifier;

    /** The node for `class` in both class declarations and class expressions. */
    final Node classNode;

    /**
     * The final post-normalized names for the class and extends clause. These may or may not match
     * the original names (if there were any original names).
     */
    final NormalizedNames normalizedNames;

    /** Instance fields in the class. */
    final Deque<Node> instanceMembers = new ArrayDeque<>();

    /** Static fields + static blocks */
    final Deque<Node> staticMembers = new ArrayDeque<>();

    /** computed props with side effects */
    final Deque<Node> computedPropsWithSideEffects = new ArrayDeque<>();

    /** Set of all the Vars defined in the constructor arguments scope and constructor body scope */
    ImmutableSet<Var> constructorVars = ImmutableSet.of();

    /**
     * List of all the {@code super()} calls within the constructor, if any.
     *
     * <p>It's legal for classes to have more than one super() call, hence this is a list rather
     * than an {@code Optional<Node>}. However, public class field transpilation will throw an error
     * if this list has more than one entry in a class with a public field; see {@link
     * Es6NormalizeClasses#ensureSuperCallIsOwnStatement}. We wait to emit this error until after
     * traversing the entire class body to find public fields.
     */
    final List<Node> superCalls = new ArrayList<>();

    ClassRecord(NormalizedNames normalizedNames, Optional<Node> bindingIdentifier, Node classNode) {
      this.normalizedNames = normalizedNames;
      this.bindingIdentifier = bindingIdentifier;
      this.classNode = classNode;
    }

    void recordField(Node field) {
      checkArgument(field.isComputedFieldDef() || field.isMemberFieldDef());
      if (field.isStaticMember()) {
        staticMembers.add(field);
      } else {
        instanceMembers.add(field);
      }
    }

    void maybeRecordComputedPropWithSideEffects(Node computedProp) {
      checkArgument(computedProp.isComputedProp() || computedProp.isComputedFieldDef());

      if (NodeUtil.canBeSideEffected(computedProp.getFirstChild())) {
        computedPropsWithSideEffects.add(computedProp);
      }
    }

    void recordStaticBlock(Node block) {
      checkArgument(NodeUtil.isClassStaticBlock(block));
      staticMembers.add(block);
    }

    void recordConstructorScope(Scope s) {
      checkArgument(s.isFunctionBlockScope(), s);
      checkState(constructorVars.isEmpty(), constructorVars);
      Scope argsScope = s.getParent();
      constructorVars =
          ImmutableSet.<Var>builder()
              .addAll(s.getAllSymbols())
              .addAll(argsScope.getAllSymbols())
              .build();
    }

    Node createNewNameReferenceNode() {
      if (normalizedNames.classNameNode().isName()) {
        // Don't cloneTree() here, because the name may have a child node, the class itself.
        return normalizedNames.classNameNode().cloneNode();
      }

      // Must cloneTree() for a qualified name.
      return normalizedNames.classNameNode().cloneTree();
    }

    Node createNewSuperclassReferenceNode() {
      if (normalizedNames.superClassNode().isEmpty()) {
        throw new IllegalArgumentException("no superclass");
      }
      return normalizedNames.superClassNode().get().cloneTree();
    }
  }

  /**
   * Information about a class *after* it has been normalized.
   *
   * <p>This is used to store information about the class that is potentially computed during the
   * normalization process. The nodes are not guaranteed to be present in the original AST.
   *
   * @param classNameNode The node for the qualified name of the class.
   *     <p>{@code "C"} as in:
   *     <ul>
   *       <li>{@code class C {}}
   *       <li>{@code const C = class D {};}
   *       <li>{@code const C = class {};}
   *     </ul>
   *     <p>{@code "ns.C"} as in:
   *     <ul>
   *       <li>{@code const ns = {}; ns.C = class {};}
   *     </ul>
   *
   * @param superClassNode The name node of the super class, if present.
   *     <p>The node for {@code E} as in:
   *     <ul>
   *       <li>{@code class C extends E {}}
   *       <li>{@code const D = class C extends E {};}
   *       <li>{@code const D = class extends E {};}
   *     </ul>
   *
   * @param shouldExtractClass Whether the class needs to be extracted into a new variable.
   * @param shouldExtractExtends Whether the extends clause needs to be extracted into a new
   *     variable.
   */
  private record NormalizedNames(
      Node classNameNode,
      Optional<Node> superClassNode,
      boolean shouldExtractClass,
      boolean shouldExtractExtends) {
    NormalizedNames {
      checkArgument(classNameNode.isQualifiedName(), classNameNode);
      checkArgument(
          superClassNode.isEmpty() || superClassNode.get().isQualifiedName(), superClassNode);
    }
  }

  /**
   * Checks whether the class and/or extends clause need to be normalized into a separate variable
   * declaration. If so, generates a new unique name/names. Returns the {@link NormalizedNames} with
   * the results. (If the class does not need normalization, then the {@link NormalizedNames} will
   * match the original class name and extends clause.)
   */
  private NormalizedNames generateNormalizedClassNames(NodeTraversal t, Node classNode) {
    Node extendsClause = classNode.getSecondChild();

    boolean shouldExtractExtends = shouldExtractExtends(classNode);
    Optional<Node> superClass;
    if (shouldExtractExtends) {
      String name = generateUniqueClassExtendsVarName(t);
      superClass = Optional.of(astFactory.createName(name, type(extendsClause)));
    } else {
      superClass = extendsClause.isEmpty() ? Optional.empty() : Optional.of(extendsClause);
    }

    boolean shouldExtractClass =
        shouldExtractClass(classNode)
            || (shouldExtractExtends && !canExtractExtendsSimply(classNode));
    Node classNameNodeTemplate;
    if (shouldExtractClass) {
      String name = generateUniqueClassDeclVarName(t);
      classNameNodeTemplate = astFactory.createConstantName(name, type(classNode));
    } else {
      classNameNodeTemplate = NodeUtil.getNameNode(classNode);
    }

    return new NormalizedNames(
        classNameNodeTemplate, superClass, shouldExtractClass, shouldExtractExtends);
  }

  /**
   * Returns true if evaluating the receiver expression twice could introduce side effects or alter
   * state. Side-effect-free receivers like {@code this} or simple variable names do not need a temp
   * variable.
   */
  private boolean receiverNeedsTempVar(Node receiver) {
    return !receiver.isThis() && !receiver.isName();
  }

  /**
   * Finds the enclosing block or script where temporary variable declarations (e.g. {@code let
   * $jscomp$tmp$...}) can be safely inserted.
   */
  private Node getDeclarationInsertionPoint(Node n, NodeTraversal t) {
    Node enclosingStmt = NodeUtil.getEnclosingStatement(n);
    if (enclosingStmt != null && enclosingStmt.getParent() != null) {
      return enclosingStmt.getParent();
    }
    return t.getScopeRoot();
  }

  /**
   * Returns true if the node represents a private member declaration (field, method, or accessor)
   * with a private identifier starting with '#'.
   */
  private static boolean isPrivateMember(Node n) {
    return n.isPrivateIdentifier() || (n.hasChildren() && n.getFirstChild().isPrivateIdentifier());
  }
}
