<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!--NewPage-->
<HTML>
<HEAD>
<!-- Generated by javadoc (build 1.6.0_0) on Fri Nov 06 20:16:46 EST 2009 -->
<TITLE>
Context (Compiler)
</TITLE>

<META NAME="date" CONTENT="2009-11-06">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../../../../dev_javadoc.css" TITLE="Style">

<SCRIPT type="text/javascript">
function windowTitle()
{
    if (location.href.indexOf('is-external=true') == -1) {
        parent.document.title="Context (Compiler)";
    }
}
</SCRIPT>
<NOSCRIPT>
</NOSCRIPT>

</HEAD>

<BODY BGCOLOR="white" onload="windowTitle();">
<HR>


<!-- ========= START OF TOP NAVBAR ======= -->
<A NAME="navbar_top"><!-- --></A>
<A HREF="#skip-navbar_top" title="Skip navigation links"></A>
<TABLE BORDER="0" WIDTH="100%" CELLPADDING="1" CELLSPACING="0" SUMMARY="">
<TR>
<TD COLSPAN=2 BGCOLOR="#EEEEFF" CLASS="NavBarCell1">
<A NAME="navbar_top_firstrow"><!-- --></A>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="3" SUMMARY="">
  <TR ALIGN="center" VALIGN="top">
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../overview-summary.html"><FONT CLASS="NavBarFont1"><B>Overview</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-summary.html"><FONT CLASS="NavBarFont1"><B>Package</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#FFFFFF" CLASS="NavBarCell1Rev"> &nbsp;<FONT CLASS="NavBarFont1Rev"><B>Class</B></FONT>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-tree.html"><FONT CLASS="NavBarFont1"><B>Tree</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../deprecated-list.html"><FONT CLASS="NavBarFont1"><B>Deprecated</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../index-all.html"><FONT CLASS="NavBarFont1"><B>Index</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../help-doc.html"><FONT CLASS="NavBarFont1"><B>Help</B></FONT></A>&nbsp;</TD>
  </TR>
</TABLE>
</TD>
<TD ALIGN="right" VALIGN="top" ROWSPAN=3><EM>
</EM>
</TD>
</TR>

<TR>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
&nbsp;<A HREF="../../../../com/google/javascript/rhino/CompilerEnvirons.html" title="class in com.google.javascript.rhino"><B>PREV CLASS</B></A>&nbsp;
&nbsp;<A HREF="../../../../com/google/javascript/rhino/Decompiler.html" title="class in com.google.javascript.rhino"><B>NEXT CLASS</B></A></FONT></TD>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
  <A HREF="../../../../index.html?com/google/javascript/rhino/Context.html" target="_top"><B>FRAMES</B></A>  &nbsp;
&nbsp;<A HREF="Context.html" target="_top"><B>NO FRAMES</B></A>  &nbsp;
&nbsp;<SCRIPT type="text/javascript">
  <!--
  if(window==top) {
    document.writeln('<A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>');
  }
  //-->
</SCRIPT>
<NOSCRIPT>
  <A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>
</NOSCRIPT>


</FONT></TD>
</TR>
<TR>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
  SUMMARY:&nbsp;NESTED&nbsp;|&nbsp;<A HREF="#field_summary">FIELD</A>&nbsp;|&nbsp;<A HREF="#constructor_summary">CONSTR</A>&nbsp;|&nbsp;<A HREF="#method_summary">METHOD</A></FONT></TD>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
DETAIL:&nbsp;<A HREF="#field_detail">FIELD</A>&nbsp;|&nbsp;<A HREF="#constructor_detail">CONSTR</A>&nbsp;|&nbsp;<A HREF="#method_detail">METHOD</A></FONT></TD>
</TR>
</TABLE>
<A NAME="skip-navbar_top"></A>
<!-- ========= END OF TOP NAVBAR ========= -->

<HR>
<!-- ======== START OF CLASS DATA ======== -->
<H2>
<FONT SIZE="-1">
com.google.javascript.rhino</FONT>
<BR>
Class Context</H2>
<PRE>
<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">java.lang.Object</A>
  <IMG SRC="../../../../resources/inherit.gif" ALT="extended by "><B>com.google.javascript.rhino.Context</B>
</PRE>
<HR>
<DL>
<DT><PRE>public class <B>Context</B><DT>extends <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A></DL>
</PRE>

<P>
This class represents the runtime context of an executing script.

 Before executing a script, an instance of Context must be created
 and associated with the thread that will be executing the script.
 The Context will be used to store information about the executing
 of the script such as the call stack. Contexts are associated with
 the current thread  using the <A HREF="../../../../com/google/javascript/rhino/Context.html#enter()"><CODE>enter()</CODE></A> method.<p>

 Different forms of script execution are supported. Scripts may be
 evaluated from the source directly, or first compiled and then later
 executed. Interactive execution is also supported.<p>

 Some aspects of script execution, such as type conversions and
 object creation, may be accessed directly through methods of
 Context.
<P>

<P>
<HR>

<P>
<!-- =========== FIELD SUMMARY =========== -->

<A NAME="field_summary"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>Field Summary</B></FONT></TH>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>[]</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#emptyArgs">emptyArgs</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Convinient value to use as zero-length array of objects.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#errorReporterProperty">errorReporterProperty</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_DYNAMIC_SCOPE">FEATURE_DYNAMIC_SCOPE</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if dynamic scope should be used for name access.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_E4X">FEATURE_E4X</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if support for E4X(ECMAScript for XML) extension is available.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_LOCATION_INFORMATION_IN_ERROR">FEATURE_LOCATION_INFORMATION_IN_ERROR</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;When the feature is on Rhino will add a "fileName" and "lineNumber"
 properties to Error objects automatically.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME">FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if member expression as function name extension is available.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_NON_ECMA_GET_YEAR">FEATURE_NON_ECMA_GET_YEAR</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Controls behaviour of <tt>Date.prototype.getYear()</tt>.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_PARENT_PROTO_PROPRTIES">FEATURE_PARENT_PROTO_PROPRTIES</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if properties <tt>__proto__</tt> and <tt>__parent__</tt>
 are treated specially.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_RESERVED_KEYWORD_AS_IDENTIFIER">FEATURE_RESERVED_KEYWORD_AS_IDENTIFIER</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if reserved keywords are treated as identifiers.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_STRICT_EVAL">FEATURE_STRICT_EVAL</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if strict eval mode is enabled.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_STRICT_MODE">FEATURE_STRICT_MODE</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Controls whether JS 1.5 'strict mode' is enabled.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_STRICT_VARS">FEATURE_STRICT_VARS</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if strict variable mode is enabled.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_TO_STRING_AS_SOURCE">FEATURE_TO_STRING_AS_SOURCE</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Control if <tt>toString()</tt> should returns the same result
 as  <tt>toSource()</tt> when applied to objects and arrays.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_WARNING_AS_ERROR">FEATURE_WARNING_AS_ERROR</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Controls whether a warning should be treated as an error.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#languageVersionProperty">languageVersionProperty</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_0">VERSION_1_0</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.0</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_1">VERSION_1_1</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.1</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_2">VERSION_1_2</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.2</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_3">VERSION_1_3</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.3</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_4">VERSION_1_4</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.4</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_5">VERSION_1_5</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.5</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_6">VERSION_1_6</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JavaScript 1.5</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_DEFAULT">VERSION_DEFAULT</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The default version.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_UNKNOWN">VERSION_UNKNOWN</A></B></CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The unknown version.</TD>
</TR>
</TABLE>
&nbsp;
<!-- ======== CONSTRUCTOR SUMMARY ======== -->

<A NAME="constructor_summary"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>Constructor Summary</B></FONT></TH>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#Context()">Context</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Create a new Context.</TD>
</TR>
</TABLE>
&nbsp;
<!-- ========== METHOD SUMMARY =========== -->

<A NAME="method_summary"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="2"><FONT SIZE="+2">
<B>Method Summary</B></FONT></TH>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#addActivationName(java.lang.String)">addActivationName</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;name)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Add a name to the list of names forcing the creation of real
 activation objects for functions.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#addPropertyChangeListener(java.beans.PropertyChangeListener)">addPropertyChangeListener</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/beans/PropertyChangeListener.html?is-external=true" title="class or interface in java.beans">PropertyChangeListener</A>&nbsp;l)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Register an object to receive notifications when a bound property
 has changed</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#checkLanguageVersion(int)">checkLanguageVersion</A></B>(int&nbsp;version)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#checkOptimizationLevel(int)">checkOptimizationLevel</A></B>(int&nbsp;optimizationLevel)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#enter()">enter</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get a context associated with the current thread, creating
 one if need be.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#enter(com.google.javascript.rhino.Context)">enter</A></B>(<A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A>&nbsp;cx)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get a Context associated with the current thread, using
 the given Context if need be.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#exit()">exit</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Exit a block of code requiring a Context.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getCurrentContext()">getCurrentContext</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get the current Context.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getDebuggerContextData()">getDebuggerContextData</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Return the debugger context data associated with current context.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino">ErrorReporter</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getErrorReporter()">getErrorReporter</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get the current error reporter.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getImplementationVersion()">getImplementationVersion</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get the implementation version.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getInstructionObserverThreshold()">getInstructionObserverThreshold</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get/Set threshold of executed instructions counter that triggers call to
 <code>observeInstructionCount()</code>.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getLanguageVersion()">getLanguageVersion</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get the current language version.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util">Locale</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getLocale()">getLocale</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get the current locale.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;int</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getOptimizationLevel()">getOptimizationLevel</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get the current optimization level.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#getThreadLocal(java.lang.Object)">getThreadLocal</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;key)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Get a value corresponding to a key.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#hasCompileFunctionsWithDynamicScope()">hasCompileFunctionsWithDynamicScope</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<B>Deprecated.</B>&nbsp;<I></I>&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>protected &nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)">hasFeature</A></B>(int&nbsp;featureIndex)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Implementation of <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int featureIndex)</CODE></A>.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isActivationNeeded(java.lang.String)">isActivationNeeded</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;name)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Check whether the name is in the list of names of objects
 forcing the creation of activation objects.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isGeneratingDebug()">isGeneratingDebug</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tell whether debug information is being generated.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isGeneratingDebugChanged()">isGeneratingDebugChanged</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isGeneratingSource()">isGeneratingSource</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tell whether source information is being generated.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isSealed()">isSealed</A></B>()</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Checks if this is a sealed Context.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isValidLanguageVersion(int)">isValidLanguageVersion</A></B>(int&nbsp;version)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;boolean</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#isValidOptimizationLevel(int)">isValidOptimizationLevel</A></B>(int&nbsp;optimizationLevel)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#putThreadLocal(java.lang.Object, java.lang.Object)">putThreadLocal</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;key,
               <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;value)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Put a value that can later be retrieved using a given key.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#removeActivationName(java.lang.String)">removeActivationName</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;name)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remove a name from the list of names forcing the creation of real
 activation objects for functions.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#removePropertyChangeListener(java.beans.PropertyChangeListener)">removePropertyChangeListener</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/beans/PropertyChangeListener.html?is-external=true" title="class or interface in java.beans">PropertyChangeListener</A>&nbsp;l)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remove an object from the list of objects registered to receive
 notification of changes to a bounded property</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#removeThreadLocal(java.lang.Object)">removeThreadLocal</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;key)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Remove values from thread-local storage.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#reportError(java.lang.String)">reportError</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Report an error using the error reporter for the current thread.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#reportError(java.lang.String, java.lang.String, int, java.lang.String, int)">reportError</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message,
            <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;sourceName,
            int&nbsp;lineno,
            <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;lineSource,
            int&nbsp;lineOffset)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Report an error using the error reporter for the current thread.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="../../../../com/google/javascript/rhino/EvaluatorException.html" title="class in com.google.javascript.rhino">EvaluatorException</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#reportRuntimeError(java.lang.String)">reportRuntimeError</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Report a runtime error using the error reporter for the current thread.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;<A HREF="../../../../com/google/javascript/rhino/EvaluatorException.html" title="class in com.google.javascript.rhino">EvaluatorException</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#reportRuntimeError(java.lang.String, java.lang.String, int, java.lang.String, int)">reportRuntimeError</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message,
                   <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;sourceName,
                   int&nbsp;lineno,
                   <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;lineSource,
                   int&nbsp;lineOffset)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Report a runtime error using the error reporter for the current thread.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#reportWarning(java.lang.String)">reportWarning</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Report a warning using the error reporter for the current thread.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>static&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#reportWarning(java.lang.String, java.lang.String, int, java.lang.String, int)">reportWarning</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message,
              <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;sourceName,
              int&nbsp;lineno,
              <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;lineSource,
              int&nbsp;lineOffset)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Report a warning using the error reporter for the current thread.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#seal(java.lang.Object)">seal</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;sealKey)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Seal this Context object so any attempt to modify any of its properties
 including calling <A HREF="../../../../com/google/javascript/rhino/Context.html#enter()"><CODE>enter()</CODE></A> and <A HREF="../../../../com/google/javascript/rhino/Context.html#exit()"><CODE>exit()</CODE></A> methods will
 throw an exception.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#setCompileFunctionsWithDynamicScope(boolean)">setCompileFunctionsWithDynamicScope</A></B>(boolean&nbsp;flag)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<B>Deprecated.</B>&nbsp;<I></I>&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino">ErrorReporter</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#setErrorReporter(com.google.javascript.rhino.ErrorReporter)">setErrorReporter</A></B>(<A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino">ErrorReporter</A>&nbsp;reporter)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Change the current error reporter.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#setGeneratingSource(boolean)">setGeneratingSource</A></B>(boolean&nbsp;generatingSource)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Specify whether or not source information should be generated.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#setInstructionObserverThreshold(int)">setInstructionObserverThreshold</A></B>(int&nbsp;threshold)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#setLanguageVersion(int)">setLanguageVersion</A></B>(int&nbsp;version)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Set the language version.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;<A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util">Locale</A></CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#setLocale(java.util.Locale)">setLocale</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util">Locale</A>&nbsp;loc)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Set the current locale.</TD>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD ALIGN="right" VALIGN="top" WIDTH="1%"><FONT SIZE="-1">
<CODE>&nbsp;void</CODE></FONT></TD>
<TD><CODE><B><A HREF="../../../../com/google/javascript/rhino/Context.html#unseal(java.lang.Object)">unseal</A></B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;sealKey)</CODE>

<BR>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Unseal previously sealed Context object.</TD>
</TR>
</TABLE>
&nbsp;<A NAME="methods_inherited_from_class_java.lang.Object"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#EEEEFF" CLASS="TableSubHeadingColor">
<TH ALIGN="left"><B>Methods inherited from class java.lang.<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A></B></TH>
</TR>
<TR BGCOLOR="white" CLASS="TableRowColor">
<TD><CODE><A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#clone()" title="class or interface in java.lang">clone</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#equals(java.lang.Object)" title="class or interface in java.lang">equals</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#finalize()" title="class or interface in java.lang">finalize</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#getClass()" title="class or interface in java.lang">getClass</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#hashCode()" title="class or interface in java.lang">hashCode</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#notify()" title="class or interface in java.lang">notify</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#notifyAll()" title="class or interface in java.lang">notifyAll</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#toString()" title="class or interface in java.lang">toString</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait()" title="class or interface in java.lang">wait</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long)" title="class or interface in java.lang">wait</A>, <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true#wait(long, int)" title="class or interface in java.lang">wait</A></CODE></TD>
</TR>
</TABLE>
&nbsp;
<P>

<!-- ============ FIELD DETAIL =========== -->

<A NAME="field_detail"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="1"><FONT SIZE="+2">
<B>Field Detail</B></FONT></TH>
</TR>
</TABLE>

<A NAME="VERSION_UNKNOWN"><!-- --></A><H3>
VERSION_UNKNOWN</H3>
<PRE>
public static final int <B>VERSION_UNKNOWN</B></PRE>
<DL>
<DD>The unknown version.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_UNKNOWN">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_DEFAULT"><!-- --></A><H3>
VERSION_DEFAULT</H3>
<PRE>
public static final int <B>VERSION_DEFAULT</B></PRE>
<DL>
<DD>The default version.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_DEFAULT">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_0"><!-- --></A><H3>
VERSION_1_0</H3>
<PRE>
public static final int <B>VERSION_1_0</B></PRE>
<DL>
<DD>JavaScript 1.0
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_0">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_1"><!-- --></A><H3>
VERSION_1_1</H3>
<PRE>
public static final int <B>VERSION_1_1</B></PRE>
<DL>
<DD>JavaScript 1.1
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_1">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_2"><!-- --></A><H3>
VERSION_1_2</H3>
<PRE>
public static final int <B>VERSION_1_2</B></PRE>
<DL>
<DD>JavaScript 1.2
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_2">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_3"><!-- --></A><H3>
VERSION_1_3</H3>
<PRE>
public static final int <B>VERSION_1_3</B></PRE>
<DL>
<DD>JavaScript 1.3
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_3">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_4"><!-- --></A><H3>
VERSION_1_4</H3>
<PRE>
public static final int <B>VERSION_1_4</B></PRE>
<DL>
<DD>JavaScript 1.4
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_4">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_5"><!-- --></A><H3>
VERSION_1_5</H3>
<PRE>
public static final int <B>VERSION_1_5</B></PRE>
<DL>
<DD>JavaScript 1.5
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_5">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="VERSION_1_6"><!-- --></A><H3>
VERSION_1_6</H3>
<PRE>
public static final int <B>VERSION_1_6</B></PRE>
<DL>
<DD>JavaScript 1.5
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.VERSION_1_6">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_NON_ECMA_GET_YEAR"><!-- --></A><H3>
FEATURE_NON_ECMA_GET_YEAR</H3>
<PRE>
public static final int <B>FEATURE_NON_ECMA_GET_YEAR</B></PRE>
<DL>
<DD>Controls behaviour of <tt>Date.prototype.getYear()</tt>.
 If <tt>hasFeature(FEATURE_NON_ECMA_GET_YEAR)</tt> returns true,
 Date.prototype.getYear subtructs 1900 only if 1900 <= date < 2000.
 The default behavior of <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> is always to subtruct
 1900 as rquired by ECMAScript B.2.4.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_NON_ECMA_GET_YEAR">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME"><!-- --></A><H3>
FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME</H3>
<PRE>
public static final int <B>FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME</B></PRE>
<DL>
<DD>Control if member expression as function name extension is available.
 If <tt>hasFeature(FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME)</tt> returns
 true, allow <tt>function memberExpression(args) { body }</tt> to be
 syntax sugar for <tt>memberExpression = function(args) { body }</tt>,
 when memberExpression is not a simple identifier.
 See ECMAScript-262, section 11.2 for definition of memberExpression.
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_MEMBER_EXPR_AS_FUNCTION_NAME">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_RESERVED_KEYWORD_AS_IDENTIFIER"><!-- --></A><H3>
FEATURE_RESERVED_KEYWORD_AS_IDENTIFIER</H3>
<PRE>
public static final int <B>FEATURE_RESERVED_KEYWORD_AS_IDENTIFIER</B></PRE>
<DL>
<DD>Control if reserved keywords are treated as identifiers.
 If <tt>hasFeature(RESERVED_KEYWORD_AS_IDENTIFIER)</tt> returns true,
 treat future reserved keyword (see  Ecma-262, section 7.5.3) as ordinary
 identifiers but warn about this usage.

 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_RESERVED_KEYWORD_AS_IDENTIFIER">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_TO_STRING_AS_SOURCE"><!-- --></A><H3>
FEATURE_TO_STRING_AS_SOURCE</H3>
<PRE>
public static final int <B>FEATURE_TO_STRING_AS_SOURCE</B></PRE>
<DL>
<DD>Control if <tt>toString()</tt> should returns the same result
 as  <tt>toSource()</tt> when applied to objects and arrays.
 If <tt>hasFeature(FEATURE_TO_STRING_AS_SOURCE)</tt> returns true,
 calling <tt>toString()</tt> on JS objects gives the same result as
 calling <tt>toSource()</tt>. That is it returns JS source with code
 to create an object with all enumeratable fields of the original object.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns true only if
 the current JS version is set to <A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_2"><CODE>VERSION_1_2</CODE></A>.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_TO_STRING_AS_SOURCE">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_PARENT_PROTO_PROPRTIES"><!-- --></A><H3>
FEATURE_PARENT_PROTO_PROPRTIES</H3>
<PRE>
public static final int <B>FEATURE_PARENT_PROTO_PROPRTIES</B></PRE>
<DL>
<DD>Control if properties <tt>__proto__</tt> and <tt>__parent__</tt>
 are treated specially.
 If <tt>hasFeature(FEATURE_PARENT_PROTO_PROPRTIES)</tt> returns true,
 treat <tt>__parent__</tt> and <tt>__proto__</tt> as special properties.
 <p>
 The properties allow to query and set scope and prototype chains for the
 objects. The special meaning of the properties is available
 only when they are used as the right hand side of the dot operator.
 For example, while <tt>x.__proto__ = y</tt> changes the prototype
 chain of the object <tt>x</tt> to point to <tt>y</tt>,
 <tt>x["__proto__"] = y</tt> simply assigns a new value to the property
 <tt>__proto__</tt> in <tt>x</tt> even when the feature is on.

 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns true.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_PARENT_PROTO_PROPRTIES">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_E4X"><!-- --></A><H3>
FEATURE_E4X</H3>
<PRE>
public static final int <B>FEATURE_E4X</B></PRE>
<DL>
<DD>Control if support for E4X(ECMAScript for XML) extension is available.
 If hasFeature(FEATURE_E4X) returns true, the XML syntax is available.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns true if
 the current JS version is set to <A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_DEFAULT"><CODE>VERSION_DEFAULT</CODE></A>
 or is greater then <A HREF="../../../../com/google/javascript/rhino/Context.html#VERSION_1_6"><CODE>VERSION_1_6</CODE></A>.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 1</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_E4X">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_DYNAMIC_SCOPE"><!-- --></A><H3>
FEATURE_DYNAMIC_SCOPE</H3>
<PRE>
public static final int <B>FEATURE_DYNAMIC_SCOPE</B></PRE>
<DL>
<DD>Control if dynamic scope should be used for name access.
 If hasFeature(FEATURE_DYNAMIC_SCOPE) returns true, then the name lookup
 during name resolution will use the top scope of the script or function
 which is at the top of JS execution stack instead of the top scope of the
 script or function from the current stack frame if the top scope of
 the top stack frame contains the top scope of the current stack frame
 on its prototype chain.
 <p>
 This is useful to define shared scope containing functions that can
 be called from scripts and functions using private scopes.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 1</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_DYNAMIC_SCOPE">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_STRICT_VARS"><!-- --></A><H3>
FEATURE_STRICT_VARS</H3>
<PRE>
public static final int <B>FEATURE_STRICT_VARS</B></PRE>
<DL>
<DD>Control if strict variable mode is enabled.
 When the feature is on Rhino reports runtime errors if assignment
 to a global variable that does not exist is executed. When the feature
 is off such assignments creates new variable in the global scope  as
 required by ECMA 262.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 1</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_STRICT_VARS">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_STRICT_EVAL"><!-- --></A><H3>
FEATURE_STRICT_EVAL</H3>
<PRE>
public static final int <B>FEATURE_STRICT_EVAL</B></PRE>
<DL>
<DD>Control if strict eval mode is enabled.
 When the feature is on Rhino reports runtime errors if non-string
 argument is passed to the eval function. When the feature is off
 eval simply return non-string argument as is without performing any
 evaluation as required by ECMA 262.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 1</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_STRICT_EVAL">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_LOCATION_INFORMATION_IN_ERROR"><!-- --></A><H3>
FEATURE_LOCATION_INFORMATION_IN_ERROR</H3>
<PRE>
public static final int <B>FEATURE_LOCATION_INFORMATION_IN_ERROR</B></PRE>
<DL>
<DD>When the feature is on Rhino will add a "fileName" and "lineNumber"
 properties to Error objects automatically. When the feature is off, you
 have to explicitly pass them as the second and third argument to the
 Error constructor. Note that neither behaviour is fully ECMA 262
 compliant (as 262 doesn't specify a three-arg constructor), but keeping
 the feature off results in Error objects that don't have
 additional non-ECMA properties when constructed using the ECMA-defined
 single-arg constructor and is thus desirable if a stricter ECMA
 compliance is desired, specifically adherence to the point 15.11.5. of
 the standard.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 6</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_LOCATION_INFORMATION_IN_ERROR">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_STRICT_MODE"><!-- --></A><H3>
FEATURE_STRICT_MODE</H3>
<PRE>
public static final int <B>FEATURE_STRICT_MODE</B></PRE>
<DL>
<DD>Controls whether JS 1.5 'strict mode' is enabled.
 When the feature is on, Rhino reports more than a dozen different
 warnings.  When the feature is off, these warnings are not generated.
 FEATURE_STRICT_MODE implies FEATURE_STRICT_VARS and FEATURE_STRICT_EVAL.
 <p>
 By default <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A> returns false.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 6</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_STRICT_MODE">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="FEATURE_WARNING_AS_ERROR"><!-- --></A><H3>
FEATURE_WARNING_AS_ERROR</H3>
<PRE>
public static final int <B>FEATURE_WARNING_AS_ERROR</B></PRE>
<DL>
<DD>Controls whether a warning should be treated as an error.
<P>
<DL>
<DT><B>Since:</B></DT>
  <DD>1.6 Release 6</DD>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.FEATURE_WARNING_AS_ERROR">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="languageVersionProperty"><!-- --></A><H3>
languageVersionProperty</H3>
<PRE>
public static final <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A> <B>languageVersionProperty</B></PRE>
<DL>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.languageVersionProperty">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="errorReporterProperty"><!-- --></A><H3>
errorReporterProperty</H3>
<PRE>
public static final <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A> <B>errorReporterProperty</B></PRE>
<DL>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../constant-values.html#com.google.javascript.rhino.Context.errorReporterProperty">Constant Field Values</A></DL>
</DL>
<HR>

<A NAME="emptyArgs"><!-- --></A><H3>
emptyArgs</H3>
<PRE>
public static final <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>[] <B>emptyArgs</B></PRE>
<DL>
<DD>Convinient value to use as zero-length array of objects.
<P>
<DL>
</DL>
</DL>

<!-- ========= CONSTRUCTOR DETAIL ======== -->

<A NAME="constructor_detail"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="1"><FONT SIZE="+2">
<B>Constructor Detail</B></FONT></TH>
</TR>
</TABLE>

<A NAME="Context()"><!-- --></A><H3>
Context</H3>
<PRE>
public <B>Context</B>()</PRE>
<DL>
<DD>Create a new Context.

 Note that the Context must be associated with a thread before
 it can be used to execute a script.
<P>
<DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#enter()"><CODE>enter()</CODE></A></DL>
</DL>

<!-- ============ METHOD DETAIL ========== -->

<A NAME="method_detail"><!-- --></A>
<TABLE BORDER="1" WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR BGCOLOR="#CCCCFF" CLASS="TableHeadingColor">
<TH ALIGN="left" COLSPAN="1"><FONT SIZE="+2">
<B>Method Detail</B></FONT></TH>
</TR>
</TABLE>

<A NAME="enter()"><!-- --></A><H3>
enter</H3>
<PRE>
public static <A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A> <B>enter</B>()</PRE>
<DL>
<DD>Get a context associated with the current thread, creating
 one if need be.

 The Context stores the execution state of the JavaScript
 engine, so it is required that the context be entered
 before execution may begin. Once a thread has entered
 a Context, then getCurrentContext() may be called to find
 the context that is associated with the current thread.
 <p>
 Calling <code>enter()</code> will
 return either the Context currently associated with the
 thread, or will create a new context and associate it
 with the current thread. Each call to <code>enter()</code>
 must have a matching call to <code>exit()</code>. For example,
 <pre>
      Context cx = Context.enter();
      try {
          ...
          cx.evaluateString(...);
      }
      finally { Context.exit(); }
 </pre>
<P>
<DD><DL>

<DT><B>Returns:</B><DD>a Context associated with the current thread<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#getCurrentContext()"><CODE>getCurrentContext()</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#exit()"><CODE>exit()</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="enter(com.google.javascript.rhino.Context)"><!-- --></A><H3>
enter</H3>
<PRE>
public static <A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A> <B>enter</B>(<A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A>&nbsp;cx)</PRE>
<DL>
<DD>Get a Context associated with the current thread, using
 the given Context if need be.
 <p>
 The same as <code>enter()</code> except that <code>cx</code>
 is associated with the current thread and returned if
 the current thread has no associated context and <code>cx</code>
 is not associated with any other thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>cx</CODE> - a Context to associate with the thread if possible
<DT><B>Returns:</B><DD>a Context associated with the current thread</DL>
</DD>
</DL>
<HR>

<A NAME="exit()"><!-- --></A><H3>
exit</H3>
<PRE>
public static void <B>exit</B>()</PRE>
<DL>
<DD>Exit a block of code requiring a Context.

 Calling <code>exit()</code> will remove the association between
 the current thread and a Context if the prior call to
 <code>enter()</code> on this thread newly associated a Context
 with this thread.
 Once the current thread no longer has an associated Context,
 it cannot be used to execute JavaScript until it is again associated
 with a Context.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#enter()"><CODE>enter()</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="getCurrentContext()"><!-- --></A><H3>
getCurrentContext</H3>
<PRE>
public static <A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino">Context</A> <B>getCurrentContext</B>()</PRE>
<DL>
<DD>Get the current Context.

 The current Context is per-thread; this method looks up
 the Context associated with the current thread. <p>
<P>
<DD><DL>

<DT><B>Returns:</B><DD>the Context associated with the current thread, or
         null if no context is associated with the current
         thread.</DL>
</DD>
</DL>
<HR>

<A NAME="isSealed()"><!-- --></A><H3>
isSealed</H3>
<PRE>
public final boolean <B>isSealed</B>()</PRE>
<DL>
<DD>Checks if this is a sealed Context. A sealed Context instance does not
 allow to modify any of its properties and will throw an exception
 on any such attempt.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#seal(java.lang.Object)"><CODE>seal(Object sealKey)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="seal(java.lang.Object)"><!-- --></A><H3>
seal</H3>
<PRE>
public final void <B>seal</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;sealKey)</PRE>
<DL>
<DD>Seal this Context object so any attempt to modify any of its properties
 including calling <A HREF="../../../../com/google/javascript/rhino/Context.html#enter()"><CODE>enter()</CODE></A> and <A HREF="../../../../com/google/javascript/rhino/Context.html#exit()"><CODE>exit()</CODE></A> methods will
 throw an exception.
 <p>
 If <tt>sealKey</tt> is not null, calling
 <A HREF="../../../../com/google/javascript/rhino/Context.html#unseal(java.lang.Object)"><CODE>unseal(Object sealKey)</CODE></A> with the same key unseals
 the object. If <tt>sealKey</tt> is null, unsealing is no longer possible.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#isSealed()"><CODE>isSealed()</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#unseal(java.lang.Object)"><CODE>unseal(Object)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="unseal(java.lang.Object)"><!-- --></A><H3>
unseal</H3>
<PRE>
public final void <B>unseal</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;sealKey)</PRE>
<DL>
<DD>Unseal previously sealed Context object.
 The <tt>sealKey</tt> argument should not be null and should match
 <tt>sealKey</tt> suplied with the last call to
 <A HREF="../../../../com/google/javascript/rhino/Context.html#seal(java.lang.Object)"><CODE>seal(Object)</CODE></A> or an exception will be thrown.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#isSealed()"><CODE>isSealed()</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#seal(java.lang.Object)"><CODE>seal(Object sealKey)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="getLanguageVersion()"><!-- --></A><H3>
getLanguageVersion</H3>
<PRE>
public final int <B>getLanguageVersion</B>()</PRE>
<DL>
<DD>Get the current language version.
 <p>
 The language version number affects JavaScript semantics as detailed
 in the overview documentation.
<P>
<DD><DL>

<DT><B>Returns:</B><DD>an integer that is one of VERSION_1_0, VERSION_1_1, etc.</DL>
</DD>
</DL>
<HR>

<A NAME="setLanguageVersion(int)"><!-- --></A><H3>
setLanguageVersion</H3>
<PRE>
public void <B>setLanguageVersion</B>(int&nbsp;version)</PRE>
<DL>
<DD>Set the language version.

 <p>
 Setting the language version will affect functions and scripts compiled
 subsequently. See the overview documentation for version-specific
 behavior.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>version</CODE> - the version as specified by VERSION_1_0, VERSION_1_1, etc.</DL>
</DD>
</DL>
<HR>

<A NAME="isValidLanguageVersion(int)"><!-- --></A><H3>
isValidLanguageVersion</H3>
<PRE>
public static boolean <B>isValidLanguageVersion</B>(int&nbsp;version)</PRE>
<DL>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="checkLanguageVersion(int)"><!-- --></A><H3>
checkLanguageVersion</H3>
<PRE>
public static void <B>checkLanguageVersion</B>(int&nbsp;version)</PRE>
<DL>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="getImplementationVersion()"><!-- --></A><H3>
getImplementationVersion</H3>
<PRE>
public final <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A> <B>getImplementationVersion</B>()</PRE>
<DL>
<DD>Get the implementation version.

 <p>
 The implementation version is of the form
 <pre>
    "<i>name langVer</i> <code>release</code> <i>relNum date</i>"
 </pre>
 where <i>name</i> is the name of the product, <i>langVer</i> is
 the language version, <i>relNum</i> is the release number, and
 <i>date</i> is the release date for that specific
 release in the form "yyyy mm dd".
<P>
<DD><DL>

<DT><B>Returns:</B><DD>a string that encodes the product, language version, release
         number, and date.</DL>
</DD>
</DL>
<HR>

<A NAME="getErrorReporter()"><!-- --></A><H3>
getErrorReporter</H3>
<PRE>
public final <A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino">ErrorReporter</A> <B>getErrorReporter</B>()</PRE>
<DL>
<DD>Get the current error reporter.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="setErrorReporter(com.google.javascript.rhino.ErrorReporter)"><!-- --></A><H3>
setErrorReporter</H3>
<PRE>
public final <A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino">ErrorReporter</A> <B>setErrorReporter</B>(<A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino">ErrorReporter</A>&nbsp;reporter)</PRE>
<DL>
<DD>Change the current error reporter.
<P>
<DD><DL>

<DT><B>Returns:</B><DD>the previous error reporter<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="getLocale()"><!-- --></A><H3>
getLocale</H3>
<PRE>
public final <A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util">Locale</A> <B>getLocale</B>()</PRE>
<DL>
<DD>Get the current locale.  Returns the default locale if none has
 been set.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util"><CODE>Locale</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="setLocale(java.util.Locale)"><!-- --></A><H3>
setLocale</H3>
<PRE>
public final <A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util">Locale</A> <B>setLocale</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util">Locale</A>&nbsp;loc)</PRE>
<DL>
<DD>Set the current locale.
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="http://java.sun.com/javase/6/docs/api/java/util/Locale.html?is-external=true" title="class or interface in java.util"><CODE>Locale</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="addPropertyChangeListener(java.beans.PropertyChangeListener)"><!-- --></A><H3>
addPropertyChangeListener</H3>
<PRE>
public final void <B>addPropertyChangeListener</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/beans/PropertyChangeListener.html?is-external=true" title="class or interface in java.beans">PropertyChangeListener</A>&nbsp;l)</PRE>
<DL>
<DD>Register an object to receive notifications when a bound property
 has changed
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>l</CODE> - the listener<DT><B>See Also:</B><DD><A HREF="http://java.sun.com/javase/6/docs/api/java/beans/PropertyChangeEvent.html?is-external=true" title="class or interface in java.beans"><CODE>PropertyChangeEvent</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#removePropertyChangeListener(java.beans.PropertyChangeListener)"><CODE>removePropertyChangeListener(java.beans.PropertyChangeListener)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="removePropertyChangeListener(java.beans.PropertyChangeListener)"><!-- --></A><H3>
removePropertyChangeListener</H3>
<PRE>
public final void <B>removePropertyChangeListener</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/beans/PropertyChangeListener.html?is-external=true" title="class or interface in java.beans">PropertyChangeListener</A>&nbsp;l)</PRE>
<DL>
<DD>Remove an object from the list of objects registered to receive
 notification of changes to a bounded property
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>l</CODE> - the listener<DT><B>See Also:</B><DD><A HREF="http://java.sun.com/javase/6/docs/api/java/beans/PropertyChangeEvent.html?is-external=true" title="class or interface in java.beans"><CODE>PropertyChangeEvent</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#addPropertyChangeListener(java.beans.PropertyChangeListener)"><CODE>addPropertyChangeListener(java.beans.PropertyChangeListener)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="reportWarning(java.lang.String, java.lang.String, int, java.lang.String, int)"><!-- --></A><H3>
reportWarning</H3>
<PRE>
public static void <B>reportWarning</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message,
                                 <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;sourceName,
                                 int&nbsp;lineno,
                                 <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;lineSource,
                                 int&nbsp;lineOffset)</PRE>
<DL>
<DD>Report a warning using the error reporter for the current thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>message</CODE> - the warning message to report<DD><CODE>sourceName</CODE> - a string describing the source, such as a filename<DD><CODE>lineno</CODE> - the starting line number<DD><CODE>lineSource</CODE> - the text of the line (may be null)<DD><CODE>lineOffset</CODE> - the offset into lineSource where problem was detected<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="reportWarning(java.lang.String)"><!-- --></A><H3>
reportWarning</H3>
<PRE>
public static void <B>reportWarning</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message)</PRE>
<DL>
<DD>Report a warning using the error reporter for the current thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>message</CODE> - the warning message to report<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="reportError(java.lang.String, java.lang.String, int, java.lang.String, int)"><!-- --></A><H3>
reportError</H3>
<PRE>
public static void <B>reportError</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message,
                               <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;sourceName,
                               int&nbsp;lineno,
                               <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;lineSource,
                               int&nbsp;lineOffset)</PRE>
<DL>
<DD>Report an error using the error reporter for the current thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>message</CODE> - the error message to report<DD><CODE>sourceName</CODE> - a string describing the source, such as a filename<DD><CODE>lineno</CODE> - the starting line number<DD><CODE>lineSource</CODE> - the text of the line (may be null)<DD><CODE>lineOffset</CODE> - the offset into lineSource where problem was detected<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="reportError(java.lang.String)"><!-- --></A><H3>
reportError</H3>
<PRE>
public static void <B>reportError</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message)</PRE>
<DL>
<DD>Report an error using the error reporter for the current thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>message</CODE> - the error message to report<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="reportRuntimeError(java.lang.String, java.lang.String, int, java.lang.String, int)"><!-- --></A><H3>
reportRuntimeError</H3>
<PRE>
public static <A HREF="../../../../com/google/javascript/rhino/EvaluatorException.html" title="class in com.google.javascript.rhino">EvaluatorException</A> <B>reportRuntimeError</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message,
                                                    <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;sourceName,
                                                    int&nbsp;lineno,
                                                    <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;lineSource,
                                                    int&nbsp;lineOffset)</PRE>
<DL>
<DD>Report a runtime error using the error reporter for the current thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>message</CODE> - the error message to report<DD><CODE>sourceName</CODE> - a string describing the source, such as a filename<DD><CODE>lineno</CODE> - the starting line number<DD><CODE>lineSource</CODE> - the text of the line (may be null)<DD><CODE>lineOffset</CODE> - the offset into lineSource where problem was detected
<DT><B>Returns:</B><DD>a runtime exception that will be thrown to terminate the
         execution of the script<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="reportRuntimeError(java.lang.String)"><!-- --></A><H3>
reportRuntimeError</H3>
<PRE>
public static <A HREF="../../../../com/google/javascript/rhino/EvaluatorException.html" title="class in com.google.javascript.rhino">EvaluatorException</A> <B>reportRuntimeError</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;message)</PRE>
<DL>
<DD>Report a runtime error using the error reporter for the current thread.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>message</CODE> - the error message to report<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/ErrorReporter.html" title="interface in com.google.javascript.rhino"><CODE>ErrorReporter</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="isGeneratingDebug()"><!-- --></A><H3>
isGeneratingDebug</H3>
<PRE>
public final boolean <B>isGeneratingDebug</B>()</PRE>
<DL>
<DD>Tell whether debug information is being generated.
<P>
<DD><DL>
<DT><B>Since:</B></DT>
  <DD>1.3</DD>
</DL>
</DD>
</DL>
<HR>

<A NAME="isGeneratingSource()"><!-- --></A><H3>
isGeneratingSource</H3>
<PRE>
public final boolean <B>isGeneratingSource</B>()</PRE>
<DL>
<DD>Tell whether source information is being generated.
<P>
<DD><DL>
<DT><B>Since:</B></DT>
  <DD>1.3</DD>
</DL>
</DD>
</DL>
<HR>

<A NAME="setGeneratingSource(boolean)"><!-- --></A><H3>
setGeneratingSource</H3>
<PRE>
public final void <B>setGeneratingSource</B>(boolean&nbsp;generatingSource)</PRE>
<DL>
<DD>Specify whether or not source information should be generated.
 <p>
 Without source information, evaluating the "toString" method
 on JavaScript functions produces only "[native code]" for
 the body of the function.
 Note that code generated without source is not fully ECMA
 conformant.
<P>
<DD><DL>
<DT><B>Since:</B></DT>
  <DD>1.3</DD>
</DL>
</DD>
</DL>
<HR>

<A NAME="getOptimizationLevel()"><!-- --></A><H3>
getOptimizationLevel</H3>
<PRE>
public final int <B>getOptimizationLevel</B>()</PRE>
<DL>
<DD>Get the current optimization level.
 <p>
 The optimization level is expressed as an integer between -1 and
 9.
<P>
<DD><DL>
<DT><B>Since:</B></DT>
  <DD>1.3</DD>
</DL>
</DD>
</DL>
<HR>

<A NAME="isValidOptimizationLevel(int)"><!-- --></A><H3>
isValidOptimizationLevel</H3>
<PRE>
public static boolean <B>isValidOptimizationLevel</B>(int&nbsp;optimizationLevel)</PRE>
<DL>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="checkOptimizationLevel(int)"><!-- --></A><H3>
checkOptimizationLevel</H3>
<PRE>
public static void <B>checkOptimizationLevel</B>(int&nbsp;optimizationLevel)</PRE>
<DL>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="getThreadLocal(java.lang.Object)"><!-- --></A><H3>
getThreadLocal</H3>
<PRE>
public final <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A> <B>getThreadLocal</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;key)</PRE>
<DL>
<DD>Get a value corresponding to a key.
 <p>
 Since the Context is associated with a thread it can be
 used to maintain values that can be later retrieved using
 the current thread.
 <p>
 Note that the values are maintained with the Context, so
 if the Context is disassociated from the thread the values
 cannot be retreived. Also, if private data is to be maintained
 in this manner the key should be a java.lang.Object
 whose reference is not divulged to untrusted code.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>key</CODE> - the key used to lookup the value
<DT><B>Returns:</B><DD>a value previously stored using putThreadLocal.</DL>
</DD>
</DL>
<HR>

<A NAME="putThreadLocal(java.lang.Object, java.lang.Object)"><!-- --></A><H3>
putThreadLocal</H3>
<PRE>
public final void <B>putThreadLocal</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;key,
                                 <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;value)</PRE>
<DL>
<DD>Put a value that can later be retrieved using a given key.
 <p>
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>key</CODE> - the key used to index the value<DD><CODE>value</CODE> - the value to save</DL>
</DD>
</DL>
<HR>

<A NAME="removeThreadLocal(java.lang.Object)"><!-- --></A><H3>
removeThreadLocal</H3>
<PRE>
public final void <B>removeThreadLocal</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A>&nbsp;key)</PRE>
<DL>
<DD>Remove values from thread-local storage.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>key</CODE> - the key for the entry to remove.<DT><B>Since:</B></DT>
  <DD>1.5 release 2</DD>
</DL>
</DD>
</DL>
<HR>

<A NAME="hasCompileFunctionsWithDynamicScope()"><!-- --></A><H3>
hasCompileFunctionsWithDynamicScope</H3>
<PRE>
<FONT SIZE="-1"><A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Deprecated.html?is-external=true" title="class or interface in java.lang">@Deprecated</A>
</FONT>public final boolean <B>hasCompileFunctionsWithDynamicScope</B>()</PRE>
<DL>
<DD><B>Deprecated.</B>&nbsp;<I></I>
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_DYNAMIC_SCOPE"><CODE>FEATURE_DYNAMIC_SCOPE</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="setCompileFunctionsWithDynamicScope(boolean)"><!-- --></A><H3>
setCompileFunctionsWithDynamicScope</H3>
<PRE>
<FONT SIZE="-1"><A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Deprecated.html?is-external=true" title="class or interface in java.lang">@Deprecated</A>
</FONT>public final void <B>setCompileFunctionsWithDynamicScope</B>(boolean&nbsp;flag)</PRE>
<DL>
<DD><B>Deprecated.</B>&nbsp;<I></I>
<P>
<DD><DL>
<DT><B>See Also:</B><DD><A HREF="../../../../com/google/javascript/rhino/Context.html#FEATURE_DYNAMIC_SCOPE"><CODE>FEATURE_DYNAMIC_SCOPE</CODE></A>, 
<A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int)</CODE></A></DL>
</DD>
</DL>
<HR>

<A NAME="getDebuggerContextData()"><!-- --></A><H3>
getDebuggerContextData</H3>
<PRE>
public final <A HREF="http://java.sun.com/javase/6/docs/api/java/lang/Object.html?is-external=true" title="class or interface in java.lang">Object</A> <B>getDebuggerContextData</B>()</PRE>
<DL>
<DD>Return the debugger context data associated with current context.
<P>
<DD><DL>

<DT><B>Returns:</B><DD>the debugger data, or null if debugger is not attached</DL>
</DD>
</DL>
<HR>

<A NAME="hasFeature(int)"><!-- --></A><H3>
hasFeature</H3>
<PRE>
protected boolean <B>hasFeature</B>(int&nbsp;featureIndex)</PRE>
<DL>
<DD>Implementation of <A HREF="../../../../com/google/javascript/rhino/Context.html#hasFeature(int)"><CODE>hasFeature(int featureIndex)</CODE></A>.
 This can be used to customize <A HREF="../../../../com/google/javascript/rhino/Context.html" title="class in com.google.javascript.rhino"><CODE>Context</CODE></A> without introducing
 additional subclasses.
<P>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="getInstructionObserverThreshold()"><!-- --></A><H3>
getInstructionObserverThreshold</H3>
<PRE>
public final int <B>getInstructionObserverThreshold</B>()</PRE>
<DL>
<DD>Get/Set threshold of executed instructions counter that triggers call to
 <code>observeInstructionCount()</code>.
 When the threshold is zero, instruction counting is disabled,
 otherwise each time the run-time executes at least the threshold value
 of script instructions, <code>observeInstructionCount()</code> will
 be called.
<P>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="setInstructionObserverThreshold(int)"><!-- --></A><H3>
setInstructionObserverThreshold</H3>
<PRE>
public final void <B>setInstructionObserverThreshold</B>(int&nbsp;threshold)</PRE>
<DL>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="isGeneratingDebugChanged()"><!-- --></A><H3>
isGeneratingDebugChanged</H3>
<PRE>
public final boolean <B>isGeneratingDebugChanged</B>()</PRE>
<DL>
<DD><DL>
</DL>
</DD>
</DL>
<HR>

<A NAME="addActivationName(java.lang.String)"><!-- --></A><H3>
addActivationName</H3>
<PRE>
public void <B>addActivationName</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;name)</PRE>
<DL>
<DD>Add a name to the list of names forcing the creation of real
 activation objects for functions.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>name</CODE> - the name of the object to add to the list</DL>
</DD>
</DL>
<HR>

<A NAME="isActivationNeeded(java.lang.String)"><!-- --></A><H3>
isActivationNeeded</H3>
<PRE>
public final boolean <B>isActivationNeeded</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;name)</PRE>
<DL>
<DD>Check whether the name is in the list of names of objects
 forcing the creation of activation objects.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>name</CODE> - the name of the object to test
<DT><B>Returns:</B><DD>true if an function activation object is needed.</DL>
</DD>
</DL>
<HR>

<A NAME="removeActivationName(java.lang.String)"><!-- --></A><H3>
removeActivationName</H3>
<PRE>
public void <B>removeActivationName</B>(<A HREF="http://java.sun.com/javase/6/docs/api/java/lang/String.html?is-external=true" title="class or interface in java.lang">String</A>&nbsp;name)</PRE>
<DL>
<DD>Remove a name from the list of names forcing the creation of real
 activation objects for functions.
<P>
<DD><DL>
<DT><B>Parameters:</B><DD><CODE>name</CODE> - the name of the object to remove from the list</DL>
</DD>
</DL>
<!-- ========= END OF CLASS DATA ========= -->
<HR>


<!-- ======= START OF BOTTOM NAVBAR ====== -->
<A NAME="navbar_bottom"><!-- --></A>
<A HREF="#skip-navbar_bottom" title="Skip navigation links"></A>
<TABLE BORDER="0" WIDTH="100%" CELLPADDING="1" CELLSPACING="0" SUMMARY="">
<TR>
<TD COLSPAN=2 BGCOLOR="#EEEEFF" CLASS="NavBarCell1">
<A NAME="navbar_bottom_firstrow"><!-- --></A>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="3" SUMMARY="">
  <TR ALIGN="center" VALIGN="top">
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../overview-summary.html"><FONT CLASS="NavBarFont1"><B>Overview</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-summary.html"><FONT CLASS="NavBarFont1"><B>Package</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#FFFFFF" CLASS="NavBarCell1Rev"> &nbsp;<FONT CLASS="NavBarFont1Rev"><B>Class</B></FONT>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="package-tree.html"><FONT CLASS="NavBarFont1"><B>Tree</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../deprecated-list.html"><FONT CLASS="NavBarFont1"><B>Deprecated</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../index-all.html"><FONT CLASS="NavBarFont1"><B>Index</B></FONT></A>&nbsp;</TD>
  <TD BGCOLOR="#EEEEFF" CLASS="NavBarCell1">    <A HREF="../../../../help-doc.html"><FONT CLASS="NavBarFont1"><B>Help</B></FONT></A>&nbsp;</TD>
  </TR>
</TABLE>
</TD>
<TD ALIGN="right" VALIGN="top" ROWSPAN=3><EM>
</EM>
</TD>
</TR>

<TR>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
&nbsp;<A HREF="../../../../com/google/javascript/rhino/CompilerEnvirons.html" title="class in com.google.javascript.rhino"><B>PREV CLASS</B></A>&nbsp;
&nbsp;<A HREF="../../../../com/google/javascript/rhino/Decompiler.html" title="class in com.google.javascript.rhino"><B>NEXT CLASS</B></A></FONT></TD>
<TD BGCOLOR="white" CLASS="NavBarCell2"><FONT SIZE="-2">
  <A HREF="../../../../index.html?com/google/javascript/rhino/Context.html" target="_top"><B>FRAMES</B></A>  &nbsp;
&nbsp;<A HREF="Context.html" target="_top"><B>NO FRAMES</B></A>  &nbsp;
&nbsp;<SCRIPT type="text/javascript">
  <!--
  if(window==top) {
    document.writeln('<A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>');
  }
  //-->
</SCRIPT>
<NOSCRIPT>
  <A HREF="../../../../allclasses-noframe.html"><B>All Classes</B></A>
</NOSCRIPT>


</FONT></TD>
</TR>
<TR>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
  SUMMARY:&nbsp;NESTED&nbsp;|&nbsp;<A HREF="#field_summary">FIELD</A>&nbsp;|&nbsp;<A HREF="#constructor_summary">CONSTR</A>&nbsp;|&nbsp;<A HREF="#method_summary">METHOD</A></FONT></TD>
<TD VALIGN="top" CLASS="NavBarCell3"><FONT SIZE="-2">
DETAIL:&nbsp;<A HREF="#field_detail">FIELD</A>&nbsp;|&nbsp;<A HREF="#constructor_detail">CONSTR</A>&nbsp;|&nbsp;<A HREF="#method_detail">METHOD</A></FONT></TD>
</TR>
</TABLE>
<A NAME="skip-navbar_bottom"></A>
<!-- ======== END OF BOTTOM NAVBAR ======= -->

<HR>

        <div id="footer">
          <div id="footerlogo">
            <img src="http://www.google.com/images/art.gif"
                 alt="Google colored balls">
          </div>

          <div id="copyright">
          <p>&copy; 2009 Google -
            <a href="http://www.google.com/privacy.html">Privacy Policy</a> -
            <a href="http://www.google.com/terms_of_service.html">Terms and Conditions</a> -
            <a href="http://www.google.com/about.html">About Google</a>
          </p>
          </div>
        </div>
      
      
</BODY>
</HTML>
